# Copyright 2024-2025 Lucas Mirelmann

module(
    name = "starlark",
    version = "0.0.1",
)

bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "google_benchmark", version = "1.9.5")
bazel_dep(name = "googletest", version = "1.18.0.bcr.1")
bazel_dep(name = "protobuf", version = "36.0.bcr.1")
bazel_dep(name = "protobuf-matchers", version = "0.1.2")
bazel_dep(name = "rules_fuzzing", version = "0.8.0")

# Added as the build is too noisy when using @20260526.0 from the dependencies.
bazel_dep(name = "abseil-cpp", version = "20260817.0")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "ucd",
    build_file_content = """
exports_files(
    glob(["**/*"]),
    visibility = ["//visibility:public"],
)
""",
    integrity = "sha256-IGbRkJsuqTkWzgktocDuSAjqPvhAfJS08U9bfrJj0o4=",
    url = "https://unicode.org/Public/17.0.0/ucd/UCD.zip",
)
