assert_false(False)
assert_true(True)
assert_true(not False)
assert_false(not True)

assert_eq(int(False), 0)
assert_eq(int(True), 1)
assert_ne(False, 0)
assert_ne(True, 1)
assert_eq(str(False), "False")
assert_eq(str(True), "True")

assert_true(True == True)
assert_false(True != True)
assert_false(False == True)
assert_true(False != True)
assert_false(True == False)
assert_true(True != False)
assert_true(False == False)
assert_false(False != False)
assert_false(True == 1)
assert_true(True != 1)

assert_true(False < True)
assert_true(False <= True)
assert_false(False >= True)
assert_false(False > True)

assert_succeed('''{True: True, False: False}''')
