# No arguments.
assert_eq(b''.strip(), b'')
assert_eq(b''.rstrip(), b'')
assert_eq(b''.lstrip(), b'')
assert_eq(b'\t'.strip(), b'')
assert_eq(b'\t'.rstrip(), b'')
assert_eq(b'\t'.lstrip(), b'')
assert_eq(b'  abc  '.strip(), b'abc')
assert_eq(b'  abc  '.rstrip(), b'  abc')
assert_eq(b'  abc  '.lstrip(), b'abc  ')
assert_eq(b'   abcdefghij  '.strip(), b'abcdefghij')
assert_eq(b'   abcdefghij  '.rstrip(), b'   abcdefghij')
assert_eq(b'   abcdefghij  '.lstrip(), b'abcdefghij  ')
assert_eq(b'  abcdefghij   '.strip(), b'abcdefghij')
assert_eq(b'  abcdefghij   '.rstrip(), b'  abcdefghij')
assert_eq(b'  abcdefghij   '.lstrip(), b'abcdefghij   ')
assert_eq(b'abcdefghij'.strip(), b'abcdefghij')
assert_eq(b'abcdefghij'.rstrip(), b'abcdefghij')
assert_eq(b'abcdefghij'.lstrip(), b'abcdefghij')
assert_eq(b'\u202Fabcdefghij\u202F'.strip(), b'\u202Fabcdefghij\u202F')
assert_eq(b'\u202Fabcdefghij\u202F'.rstrip(), b'\u202Fabcdefghij\u202F')
assert_eq(b'\u202Fabcdefghij\u202F'.lstrip(), b'\u202Fabcdefghij\u202F')

# One argument.
assert_eq(b'  abcdefghij   '.strip(None), b'abcdefghij')
assert_eq(b'  abcdefghij   '.rstrip(None), b'  abcdefghij')
assert_eq(b'  abcdefghij   '.lstrip(None), b'abcdefghij   ')
assert_eq(b''.strip(b''), b'')
assert_eq(b''.rstrip(b''), b'')
assert_eq(b''.lstrip(b''), b'')
assert_eq(b' '.strip(b''), b' ')
assert_eq(b' '.rstrip(b''), b' ')
assert_eq(b' '.lstrip(b''), b' ')
assert_eq(b' \t '.strip(b' '), b'\t')
assert_eq(b' \t '.rstrip(b' '), b' \t')
assert_eq(b' \t '.lstrip(b' '), b'\t ')
assert_eq(b'  abc  '.strip(b'x'), b'  abc  ')
assert_eq(b'  abc  '.rstrip(b'x'), b'  abc  ')
assert_eq(b'  abc  '.lstrip(b'x'), b'  abc  ')
assert_eq(b'xxabcxx'.strip(b'x'), b'abc')
assert_eq(b'xxabcxx'.rstrip(b'x'), b'xxabc')
assert_eq(b'xxabcxx'.lstrip(b'x'), b'abcxx')
assert_eq(b'zyxabcdefghijzyx'.strip(b'xyz'), b'abcdefghij')
assert_eq(b'zyxabcdefghijzyx'.rstrip(b'xyz'), b'zyxabcdefghij')
assert_eq(b'zyxabcdefghijzyx'.lstrip(b'xyz'), b'abcdefghijzyx')
assert_eq(b'abcdefghij'.strip(b'xyz'), b'abcdefghij')
assert_eq(b'abcdefghij'.rstrip(b'xyz'), b'abcdefghij')
assert_eq(b'abcdefghij'.lstrip(b'xyz'), b'abcdefghij')
assert_eq(b'zzyyxx'.strip(b'xyz'), b'')
assert_eq(b'zzyyxx'.rstrip(b'xyz'), b'')
assert_eq(b'zzyyxx'.lstrip(b'xyz'), b'')

assert_fail('''b"abc".strip(97)''')
assert_fail('''b"abc".rstrip(97)''')
assert_fail('''b"abc".lstrip(97)''')
assert_fail('''b"abc".strip(False)''')
assert_fail('''b"abc".rstrip(False)''')
assert_fail('''b"abc".lstrip(False)''')
assert_fail('''b"abc".strip(bytes = "a")''')
assert_fail('''b"abc".rstrip(bytes = "a")''')
assert_fail('''b"abc".lstrip(bytes = "a")''')
assert_fail('''b"abc".strip(cutset = "a")''')
assert_fail('''b"abc".rstrip(cutset = "a")''')
assert_fail('''b"abc".lstrip(cutset = "a")''')

