# Zero arguments.
assert_fail('''b'abc'.endswith()''')

# One argument.
assert_true(b''.endswith(b''))
assert_false(b''.endswith(b'a'))
assert_true(b'abc'.endswith(b'c'))
assert_true(b'abc'.endswith(b'abc'))
assert_true(b'abc'.endswith(b''))
assert_false(b'abc'.endswith(b'a'))
assert_false(b'abc'.endswith(b'aabc'))

assert_false(b'abc'.endswith(()))
assert_true(b''.endswith((b'',)))
assert_false(b''.endswith((b'a',)))
assert_true(b'abc'.endswith((b'c',)))
assert_true(b'abc'.endswith((b'abc',)))
assert_true(b'abc'.endswith((b'',)))
assert_false(b'abc'.endswith((b'a',)))
assert_false(b'abc'.endswith((b'aabc',)))

assert_true(b''.endswith((b'', b'a')))
assert_false(b''.endswith((b'a', b'c')))
assert_true(b'abc'.endswith((b'c', b'abc')))
assert_true(b'abc'.endswith((b'abc', b'')))
assert_true(b'abc'.endswith((b'', b'a')))
assert_false(b'abc'.endswith((b'a', b'aabc')))
assert_true(b'abc'.endswith((b'aabc', b'')))

assert_fail('''b'abc'.endswith("")''')
assert_fail('''b'abc'.endswith(97)''')
assert_fail('''b'abc'.endswith(("",))''')

# Two arguments.
assert_true(b''.endswith(b'', 0))
assert_false(b''.endswith(b'', 1))
assert_false(b''.endswith(b'a', 0))
assert_false(b''.endswith(b'a', 1))
assert_true(b'abc'.endswith(b'c', 0))
assert_true(b'abc'.endswith(b'c', 1))
assert_true(b'abc'.endswith(b'c', 2))
assert_false(b'abc'.endswith(b'c', 3))
assert_true(b'abc'.endswith(b'abc', -4))
assert_true(b'abc'.endswith(b'abc', -3))
assert_false(b'abc'.endswith(b'abc', -2))
assert_false(b'abc'.endswith(b'abc', -1))
assert_true(b'abc'.endswith(b'abc', 0))
assert_false(b'abc'.endswith(b'abc', 1))
assert_true(b'abc'.endswith(b'', 0))
assert_true(b'abc'.endswith(b'', 1))
assert_true(b'abc'.endswith(b'', 2))
assert_true(b'abc'.endswith(b'', 3))
assert_false(b'abc'.endswith(b'', 4))
assert_false(b'abc'.endswith(b'a', 0))
assert_false(b'abc'.endswith(b'a', 1))
assert_false(b'abc'.endswith(b'a', 2))
assert_false(b'abc'.endswith(b'a', 3))
assert_false(b'abc'.endswith(b'a', 4))
assert_false(b'abc'.endswith(b'aabc', -1))
assert_false(b'abc'.endswith(b'aabc', 0))
assert_false(b'abc'.endswith(b'aabc', 3))

assert_fail('''b'abc'.endswith(b'', False)''')
assert_true(b'abc'.endswith(b'abc', None))

# Three arguments.
assert_true(b''.endswith(b'', 0, -1))
assert_true(b''.endswith(b'', 0, 0))
assert_false(b''.endswith(b'', 1, 0))
assert_false(b''.endswith(b'a', 1, 0))
assert_false(b''.endswith(b'a', 1, 1))
assert_true(b'abc'.endswith(b'c', 0, 3))
assert_true(b'abc'.endswith(b'c', 2, 3))
assert_false(b'abc'.endswith(b'c', 3, 3))
assert_false(b'abc'.endswith(b'c', 1, 2))
assert_true(b'abc'.endswith(b'b', 1, 2))
assert_false(b'abc'.endswith(b'abc', 0, -1))
assert_true(b'abc'.endswith(b'ab', 0, -1))
assert_false(b'abc'.endswith(b'abc', 0, 2))
assert_true(b'abc'.endswith(b'abc', 0, 3))
assert_true(b'abc'.endswith(b'abc', 0, 4))
assert_false(b'abc'.endswith(b'abc', 1, 3))
assert_false(b'abc'.endswith(b'abc', -1, 4))
assert_false(b'abc'.endswith(b'abc', -2, 10))
assert_true(b'abc'.endswith(b'', 0, 3))
assert_true(b'abc'.endswith(b'', 2, 3))
assert_false(b'abc'.endswith(b'', 2, 1))
assert_true(b'abc'.endswith(b'', 3, 3))
assert_false(b'abc'.endswith(b'', 4, 3))
assert_false(b'abc'.endswith(b'a', 0, 3,))
assert_true(b'abc'.endswith(b'a', 0, 1))
assert_false(b'abc'.endswith(b'a', 3, 3))
assert_false(b'abc'.endswith(b'aabc', -1, 2))
assert_false(b'abc'.endswith(b'aabc', 0, 4))
assert_false(b'abc'.endswith(b'aabc', 3, 3))
assert_fail('''b'abc'.endswith(b'', 0, False)''')
assert_true(b'abc'.endswith(b'abc', None, None))

# Four arguments
assert_fail('''b''.endswith(b'', None, None, None)''')

assert_fail('''b''.endswith(suffix=b'')''')
assert_fail('''b''.endswith(b'', start = 0)''')
assert_fail('''b''.endswith(b'', 0, end = 0)''')

