# No arguments.
assert_fail('''b'abc'.index()''')
assert_fail('''b'abc'.rindex()''')


# One argument.
assert_fail('''b'abc'.index(())''')
assert_fail('''b'abc'.rindex(())''')
assert_eq(b'banana'.index(97), 1)
assert_eq(b'banana'.rindex(97), 5)
assert_fail('''b'abc'.index(True)''')
assert_fail('''b'abc'.rindex(True)''')
assert_fail('''b'abc'.index(None)''')
assert_fail('''b'abc'.rindex(None)''')

assert_eq(b'banana'.index(b''), 0)
assert_eq(b'banana'.index(b'an'), 1)
assert_eq(b'banana'.index(b'ban'), 0)
assert_fail('''b'banana'.index(b'bb')''')
assert_eq(b'banana'.rindex(b''), 6)
assert_eq(b'banana'.rindex(b'an'), 3)
assert_eq(b'banana'.rindex(b'ban'), 0)
assert_fail('''b'banana'.rindex(b'bb')''')


# Two arguments.
assert_eq(b'banana'.index(b'a', None), 1)
assert_eq(b'banana'.rindex(b'a', None), 5)
assert_fail('''b'banana'.index(b'b', False)''')
assert_fail('''b'banana'.rindex(b'b', False)''')

assert_eq(b'abab'.index(b'ab', -5), 0)
assert_eq(b'abab'.index(b'ab', -4), 0)
assert_eq(b'abab'.index(b'ab', -3), 2)
assert_eq(b'abab'.index(b'ab', -2), 2)
assert_fail('''b'abab'.index(b'ab', -1)''')
assert_eq(b'abab'.index(b'ab', 0), 0)
assert_eq(b'abab'.index(b'ab', 1), 2)
assert_eq(b'abab'.index(b'ab', 2), 2)
assert_fail('''b'abab'.index(b'ab', 3)''')
assert_fail('''b'abab'.index(b'ab', 4)''')
assert_fail('''b'abab'.index(b'ab', 5)''')

assert_eq(b'abab'.rindex(b'ab', -5), 2)
assert_eq(b'abab'.rindex(b'ab', -4), 2)
assert_eq(b'abab'.rindex(b'ab', -3), 2)
assert_eq(b'abab'.rindex(b'ab', -2), 2)
assert_fail('''b'abab'.rindex(b'ab', -1)''')
assert_eq(b'abab'.rindex(b'ab', 0), 2)
assert_eq(b'abab'.rindex(b'ab', 1), 2)
assert_eq(b'abab'.rindex(b'ab', 2), 2)
assert_fail('''b'abab'.rindex(b'ab', 3)''')
assert_fail('''b'abab'.rindex(b'ab', 4)''')
assert_fail('''b'abab'.rindex(b'ab', 5)''')


# Three arguments.
assert_eq(b''.index(b'', -1, -1), 0)
assert_eq(b''.index(b'', -1, 0), 0)
assert_eq(b''.index(b'', -1, 1), 0)
assert_eq(b''.index(b'', 0, -1), 0)
assert_eq(b''.index(b'', 0, 0), 0)
assert_eq(b''.index(b'', 0, 1), 0)
assert_fail('''b''.index(b'', 1, -1)''')
assert_fail('''b''.index(b'', 1, 0)''')
assert_fail('''b''.index(b'', 1, 1)''')

assert_eq(b''.rindex(b'', -1, -1), 0)
assert_eq(b''.rindex(b'', -1, 0), 0)
assert_eq(b''.rindex(b'', -1, 1), 0)
assert_eq(b''.rindex(b'', 0, -1), 0)
assert_eq(b''.rindex(b'', 0, 0), 0)
assert_eq(b''.rindex(b'', 0, 1), 0)
assert_fail('''b''.rindex(b'', 1, -1)''')
assert_fail('''b''.rindex(b'', 1, 0)''')
assert_fail('''b''.rindex(b'', 1, 1)''')


assert_fail('''b'abab'.index(b'ab', -5, -5)''')
assert_fail('''b'abab'.index(b'ab', -5, -4)''')
assert_fail('''b'abab'.index(b'ab', -5, -3)''')
assert_eq(b'abab'.index(b'ab', -5, -2), 0)
assert_eq(b'abab'.index(b'ab', -5, -1), 0)
assert_fail('''b'abab'.index(b'ab', -5, 0)''')
assert_fail('''b'abab'.index(b'ab', -5, 1)''')
assert_eq(b'abab'.index(b'ab', -5, 2), 0)
assert_eq(b'abab'.index(b'ab', -5, 3), 0)
assert_eq(b'abab'.index(b'ab', -5, 4), 0)
assert_eq(b'abab'.index(b'ab', -5, 5), 0)
assert_fail('''b'abab'.index(b'ab', -4, -5)''')
assert_fail('''b'abab'.index(b'ab', -4, -4)''')
assert_fail('''b'abab'.index(b'ab', -4, -3)''')
assert_eq(b'abab'.index(b'ab', -4, -2), 0)
assert_eq(b'abab'.index(b'ab', -4, -1), 0)
assert_fail('''b'abab'.index(b'ab', -4, 0)''')
assert_fail('''b'abab'.index(b'ab', -4, 1)''')
assert_eq(b'abab'.index(b'ab', -4, 2), 0)
assert_eq(b'abab'.index(b'ab', -4, 3), 0)
assert_eq(b'abab'.index(b'ab', -4, 4), 0)
assert_eq(b'abab'.index(b'ab', -4, 5), 0)
assert_fail('''b'abab'.index(b'ab', -3, -5)''')
assert_fail('''b'abab'.index(b'ab', -3, -4)''')
assert_fail('''b'abab'.index(b'ab', -3, -3)''')
assert_fail('''b'abab'.index(b'ab', -3, -2)''')
assert_fail('''b'abab'.index(b'ab', -3, -1)''')
assert_fail('''b'abab'.index(b'ab', -3, 0)''')
assert_fail('''b'abab'.index(b'ab', -3, 1)''')
assert_fail('''b'abab'.index(b'ab', -3, 2)''')
assert_fail('''b'abab'.index(b'ab', -3, 3)''')
assert_eq(b'abab'.index(b'ab', -3, 4), 2)
assert_eq(b'abab'.index(b'ab', -3, 5), 2)
assert_fail('''b'abab'.index(b'ab', -2, -5)''')
assert_fail('''b'abab'.index(b'ab', -2, -4)''')
assert_fail('''b'abab'.index(b'ab', -2, -3)''')
assert_fail('''b'abab'.index(b'ab', -2, -2)''')
assert_fail('''b'abab'.index(b'ab', -2, -1)''')
assert_fail('''b'abab'.index(b'ab', -2, 0)''')
assert_fail('''b'abab'.index(b'ab', -2, 1)''')
assert_fail('''b'abab'.index(b'ab', -2, 2)''')
assert_fail('''b'abab'.index(b'ab', -2, 3)''')
assert_eq(b'abab'.index(b'ab', -2, 4), 2)
assert_eq(b'abab'.index(b'ab', -2, 5), 2)
assert_fail('''b'abab'.index(b'ab', -1, -5)''')
assert_fail('''b'abab'.index(b'ab', -1, -4)''')
assert_fail('''b'abab'.index(b'ab', -1, -3)''')
assert_fail('''b'abab'.index(b'ab', -1, -2)''')
assert_fail('''b'abab'.index(b'ab', -1, -1)''')
assert_fail('''b'abab'.index(b'ab', -1, 0)''')
assert_fail('''b'abab'.index(b'ab', -1, 1)''')
assert_fail('''b'abab'.index(b'ab', -1, 2)''')
assert_fail('''b'abab'.index(b'ab', -1, 3)''')
assert_fail('''b'abab'.index(b'ab', -1, 4)''')
assert_fail('''b'abab'.index(b'ab', -1, 5)''')
assert_fail('''b'abab'.index(b'ab', 0, -5)''')
assert_fail('''b'abab'.index(b'ab', 0, -4)''')
assert_fail('''b'abab'.index(b'ab', 0, -3)''')
assert_eq(b'abab'.index(b'ab', 0, -2), 0)
assert_eq(b'abab'.index(b'ab', 0, -1), 0)
assert_fail('''b'abab'.index(b'ab', 0, 0)''')
assert_fail('''b'abab'.index(b'ab', 0, 1)''')
assert_eq(b'abab'.index(b'ab', 0, 2), 0)
assert_eq(b'abab'.index(b'ab', 0, 3), 0)
assert_eq(b'abab'.index(b'ab', 0, 4), 0)
assert_eq(b'abab'.index(b'ab', 0, 5), 0)
assert_fail('''b'abab'.index(b'ab', 1, -5)''')
assert_fail('''b'abab'.index(b'ab', 1, -4)''')
assert_fail('''b'abab'.index(b'ab', 1, -3)''')
assert_fail('''b'abab'.index(b'ab', 1, -2)''')
assert_fail('''b'abab'.index(b'ab', 1, -1)''')
assert_fail('''b'abab'.index(b'ab', 1, 0)''')
assert_fail('''b'abab'.index(b'ab', 1, 1)''')
assert_fail('''b'abab'.index(b'ab', 1, 2)''')
assert_fail('''b'abab'.index(b'ab', 1, 3)''')
assert_eq(b'abab'.index(b'ab', 1, 4), 2)
assert_eq(b'abab'.index(b'ab', 1, 5), 2)
assert_fail('''b'abab'.index(b'ab', 2, -5)''')
assert_fail('''b'abab'.index(b'ab', 2, -4)''')
assert_fail('''b'abab'.index(b'ab', 2, -3)''')
assert_fail('''b'abab'.index(b'ab', 2, -2)''')
assert_fail('''b'abab'.index(b'ab', 2, -1)''')
assert_fail('''b'abab'.index(b'ab', 2, 0)''')
assert_fail('''b'abab'.index(b'ab', 2, 1)''')
assert_fail('''b'abab'.index(b'ab', 2, 2)''')
assert_fail('''b'abab'.index(b'ab', 2, 3)''')
assert_eq(b'abab'.index(b'ab', 2, 4), 2)
assert_eq(b'abab'.index(b'ab', 2, 5), 2)
assert_fail('''b'abab'.index(b'ab', 3, -5)''')
assert_fail('''b'abab'.index(b'ab', 3, -4)''')
assert_fail('''b'abab'.index(b'ab', 3, -3)''')
assert_fail('''b'abab'.index(b'ab', 3, -2)''')
assert_fail('''b'abab'.index(b'ab', 3, -1)''')
assert_fail('''b'abab'.index(b'ab', 3, 0)''')
assert_fail('''b'abab'.index(b'ab', 3, 1)''')
assert_fail('''b'abab'.index(b'ab', 3, 2)''')
assert_fail('''b'abab'.index(b'ab', 3, 3)''')
assert_fail('''b'abab'.index(b'ab', 3, 4)''')
assert_fail('''b'abab'.index(b'ab', 3, 5)''')
assert_fail('''b'abab'.index(b'ab', 4, -5)''')
assert_fail('''b'abab'.index(b'ab', 4, -4)''')
assert_fail('''b'abab'.index(b'ab', 4, -3)''')
assert_fail('''b'abab'.index(b'ab', 4, -2)''')
assert_fail('''b'abab'.index(b'ab', 4, -1)''')
assert_fail('''b'abab'.index(b'ab', 4, 0)''')
assert_fail('''b'abab'.index(b'ab', 4, 1)''')
assert_fail('''b'abab'.index(b'ab', 4, 2)''')
assert_fail('''b'abab'.index(b'ab', 4, 3)''')
assert_fail('''b'abab", "ab', 4, 4)''')
assert_fail('''b'abab'.index(b'ab', 4, 5)''')
assert_fail('''b'abab'.index(b'ab', 5, -5)''')
assert_fail('''b'abab'.index(b'ab', 5, -4)''')
assert_fail('''b'abab'.index(b'ab', 5, -3)''')
assert_fail('''b'abab'.index(b'ab', 5, -2)''')
assert_fail('''b'abab'.index(b'ab', 5, -1)''')
assert_fail('''b'abab'.index(b'ab', 5, 0)''')
assert_fail('''b'abab'.index(b'ab', 5, 1)''')
assert_fail('''b'abab'.index(b'ab', 5, 2)''')
assert_fail('''b'abab'.index(b'ab', 5, 3)''')
assert_fail('''b'abab'.index(b'ab', 5, 4)''')
assert_fail('''b'abab'.index(b'ab', 5, 5)''')

assert_fail('''b'abab'.rindex(b'ab', -5, -5)''')
assert_fail('''b'abab'.rindex(b'ab', -5, -4)''')
assert_fail('''b'abab'.rindex(b'ab', -5, -3)''')
assert_eq(b'abab'.rindex(b'ab', -5, -2), 0)
assert_eq(b'abab'.rindex(b'ab', -5, -1), 0)
assert_fail('''b'abab'.rindex(b'ab', -5, 0)''')
assert_fail('''b'abab'.rindex(b'ab', -5, 1)''')
assert_eq(b'abab'.rindex(b'ab', -5, 2), 0)
assert_eq(b'abab'.rindex(b'ab', -5, 3), 0)
assert_eq(b'abab'.rindex(b'ab', -5, 4), 2)
assert_eq(b'abab'.rindex(b'ab', -5, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', -4, -5)''')
assert_fail('''b'abab'.rindex(b'ab', -4, -4)''')
assert_fail('''b'abab'.rindex(b'ab', -4, -3)''')
assert_eq(b'abab'.rindex(b'ab', -4, -2), 0)
assert_eq(b'abab'.rindex(b'ab', -4, -1), 0)
assert_fail('''b'abab'.rindex(b'ab', -4, 0)''')
assert_fail('''b'abab'.rindex(b'ab', -4, 1)''')
assert_eq(b'abab'.rindex(b'ab', -4, 2), 0)
assert_eq(b'abab'.rindex(b'ab', -4, 3), 0)
assert_eq(b'abab'.rindex(b'ab', -4, 4), 2)
assert_eq(b'abab'.rindex(b'ab', -4, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', -3, -5)''')
assert_fail('''b'abab'.rindex(b'ab', -3, -4)''')
assert_fail('''b'abab'.rindex(b'ab', -3, -3)''')
assert_fail('''b'abab'.rindex(b'ab', -3, -2)''')
assert_fail('''b'abab'.rindex(b'ab', -3, -1)''')
assert_fail('''b'abab'.rindex(b'ab', -3, 0)''')
assert_fail('''b'abab'.rindex(b'ab', -3, 1)''')
assert_fail('''b'abab'.rindex(b'ab', -3, 2)''')
assert_fail('''b'abab'.rindex(b'ab', -3, 3)''')
assert_eq(b'abab'.rindex(b'ab', -3, 4), 2)
assert_eq(b'abab'.rindex(b'ab', -3, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', -2, -5)''')
assert_fail('''b'abab'.rindex(b'ab', -2, -4)''')
assert_fail('''b'abab'.rindex(b'ab', -2, -3)''')
assert_fail('''b'abab'.rindex(b'ab', -2, -2)''')
assert_fail('''b'abab'.rindex(b'ab', -2, -1)''')
assert_fail('''b'abab'.rindex(b'ab', -2, 0)''')
assert_fail('''b'abab'.rindex(b'ab', -2, 1)''')
assert_fail('''b'abab'.rindex(b'ab', -2, 2)''')
assert_fail('''b'abab'.rindex(b'ab', -2, 3)''')
assert_eq(b'abab'.rindex(b'ab', -2, 4), 2)
assert_eq(b'abab'.rindex(b'ab', -2, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', -1, -5)''')
assert_fail('''b'abab'.rindex(b'ab', -1, -4)''')
assert_fail('''b'abab'.rindex(b'ab', -1, -3)''')
assert_fail('''b'abab'.rindex(b'ab', -1, -2)''')
assert_fail('''b'abab'.rindex(b'ab', -1, -1)''')
assert_fail('''b'abab'.rindex(b'ab', -1, 0)''')
assert_fail('''b'abab'.rindex(b'ab', -1, 1)''')
assert_fail('''b'abab'.rindex(b'ab', -1, 2)''')
assert_fail('''b'abab'.rindex(b'ab', -1, 3)''')
assert_fail('''b'abab'.rindex(b'ab', -1, 4)''')
assert_fail('''b'abab'.rindex(b'ab', -1, 5)''')
assert_fail('''b'abab'.rindex(b'ab', 0, -5)''')
assert_fail('''b'abab'.rindex(b'ab', 0, -4)''')
assert_fail('''b'abab'.rindex(b'ab', 0, -3)''')
assert_eq(b'abab'.rindex(b'ab', 0, -2), 0)
assert_eq(b'abab'.rindex(b'ab', 0, -1), 0)
assert_fail('''b'abab'.rindex(b'ab', 0, 0)''')
assert_fail('''b'abab'.rindex(b'ab', 0, 1)''')
assert_eq(b'abab'.rindex(b'ab', 0, 2), 0)
assert_eq(b'abab'.rindex(b'ab', 0, 3), 0)
assert_eq(b'abab'.rindex(b'ab', 0, 4), 2)
assert_eq(b'abab'.rindex(b'ab', 0, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', 1, -5)''')
assert_fail('''b'abab'.rindex(b'ab', 1, -4)''')
assert_fail('''b'abab'.rindex(b'ab', 1, -3)''')
assert_fail('''b'abab'.rindex(b'ab', 1, -2)''')
assert_fail('''b'abab'.rindex(b'ab', 1, -1)''')
assert_fail('''b'abab'.rindex(b'ab', 1, 0)''')
assert_fail('''b'abab'.rindex(b'ab', 1, 1)''')
assert_fail('''b'abab'.rindex(b'ab', 1, 2)''')
assert_fail('''b'abab'.rindex(b'ab', 1, 3)''')
assert_eq(b'abab'.rindex(b'ab', 1, 4), 2)
assert_eq(b'abab'.rindex(b'ab', 1, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', 2, -5)''')
assert_fail('''b'abab'.rindex(b'ab', 2, -4)''')
assert_fail('''b'abab'.rindex(b'ab', 2, -3)''')
assert_fail('''b'abab'.rindex(b'ab', 2, -2)''')
assert_fail('''b'abab'.rindex(b'ab', 2, -1)''')
assert_fail('''b'abab'.rindex(b'ab', 2, 0)''')
assert_fail('''b'abab'.rindex(b'ab', 2, 1)''')
assert_fail('''b'abab'.rindex(b'ab', 2, 2)''')
assert_fail('''b'abab'.rindex(b'ab', 2, 3)''')
assert_eq(b'abab'.rindex(b'ab', 2, 4), 2)
assert_eq(b'abab'.rindex(b'ab', 2, 5), 2)
assert_fail('''b'abab'.rindex(b'ab', 3, -5)''')
assert_fail('''b'abab'.rindex(b'ab', 3, -4)''')
assert_fail('''b'abab'.rindex(b'ab', 3, -3)''')
assert_fail('''b'abab'.rindex(b'ab', 3, -2)''')
assert_fail('''b'abab'.rindex(b'ab', 3, -1)''')
assert_fail('''b'abab'.rindex(b'ab', 3, 0)''')
assert_fail('''b'abab'.rindex(b'ab', 3, 1)''')
assert_fail('''b'abab'.rindex(b'ab', 3, 2)''')
assert_fail('''b'abab'.rindex(b'ab', 3, 3)''')
assert_fail('''b'abab'.rindex(b'ab', 3, 4)''')
assert_fail('''b'abab'.rindex(b'ab', 3, 5)''')
assert_fail('''b'abab'.rindex(b'ab', 4, -5)''')
assert_fail('''b'abab'.rindex(b'ab', 4, -4)''')
assert_fail('''b'abab'.rindex(b'ab', 4, -3)''')
assert_fail('''b'abab'.rindex(b'ab', 4, -2)''')
assert_fail('''b'abab'.rindex(b'ab', 4, -1)''')
assert_fail('''b'abab'.rindex(b'ab', 4, 0)''')
assert_fail('''b'abab'.rindex(b'ab', 4, 1)''')
assert_fail('''b'abab'.rindex(b'ab', 4, 2)''')
assert_fail('''b'abab'.rindex(b'ab', 4, 3)''')
assert_fail('''b'abab", "ab', 4, 4)''')
assert_fail('''b'abab'.rindex(b'ab', 4, 5)''')
assert_fail('''b'abab'.rindex(b'ab', 5, -5)''')
assert_fail('''b'abab'.rindex(b'ab', 5, -4)''')
assert_fail('''b'abab'.rindex(b'ab', 5, -3)''')
assert_fail('''b'abab'.rindex(b'ab', 5, -2)''')
assert_fail('''b'abab'.rindex(b'ab', 5, -1)''')
assert_fail('''b'abab'.rindex(b'ab', 5, 0)''')
assert_fail('''b'abab'.rindex(b'ab', 5, 1)''')
assert_fail('''b'abab'.rindex(b'ab', 5, 2)''')
assert_fail('''b'abab'.rindex(b'ab', 5, 3)''')
assert_fail('''b'abab'.rindex(b'ab', 5, 4)''')
assert_fail('''b'abab'.rindex(b'ab', 5, 5)''')


# Four arguments.
assert_fail('''b'abc'.index(b'', 0, 0, 0)''')
assert_fail('''b'abc'.rindex(b'', 0, 0, 0)''')


# Named arguments.
assert_fail('''b'abc'.index(b'', start = 0)''')
assert_fail('''b'abc'.rindex(b'', start = 0)''')
assert_fail('''b'abc'.index(b'', stop = 0)''')
assert_fail('''b'abc'.rindex(b'', stop = 0)''')


