
def test(start, stop, stride, expected0, expected1, expected2, expected3, expected4, expected5):
  assert_eq(b''[start:stop:stride], expected0)
  assert_eq(b'a'[start:stop:stride], expected1)
  assert_eq(b'ab'[start:stop:stride], expected2)
  assert_eq(b'abc'[start:stop:stride], expected3)
  assert_eq(b'abcd'[start:stop:stride], expected4)
  assert_eq(b'abcde'[start:stop:stride], expected5)

test(None, None, None, b'', b'a', b'ab', b'abc', b'abcd', b'abcde')
test(None, None, -1, b'', b'a', b'ba', b'cba', b'dcba', b'edcba')
test(None, None, 1, b'', b'a', b'ab', b'abc', b'abcd', b'abcde')
test(None, -1, None, b'', b'', b'a', b'ab', b'abc', b'abcd')
test(None, -1, -1, b'', b'', b'', b'', b'', b'')
test(None, -1, 1, b'', b'', b'a', b'ab', b'abc', b'abcd')
test(None, 0, None, b'', b'', b'', b'', b'', b'')
test(None, 0, -1, b'', b'', b'b', b'cb', b'dcb', b'edcb')
test(None, 0, 1, b'', b'', b'', b'', b'', b'')
test(None, 1, None, b'', b'a', b'a', b'a', b'a', b'a')
test(None, 1, -1, b'', b'', b'', b'c', b'dc', b'edc')
test(None, 1, 1, b'', b'a', b'a', b'a', b'a', b'a')

test(-1, None, None, b'', b'a', b'b', b'c', b'd', b'e')
test(-1, None, -1, b'', b'a', b'ba', b'cba', b'dcba', b'edcba')
test(-1, None, 1, b'', b'a', b'b', b'c', b'd', b'e')
test(-1, -1, None, b'', b'', b'', b'', b'', b'')
test(-1, -1, -1, b'', b'', b'', b'', b'', b'')
test(-1, -1, 1, b'', b'', b'', b'', b'', b'')
test(-1, 0, None, b'', b'', b'', b'', b'', b'')
test(-1, 0, -1, b'', b'', b'b', b'cb', b'dcb', b'edcb')
test(-1, 0, 1, b'', b'', b'', b'', b'', b'')
test(-1, 1, None, b'', b'a', b'', b'', b'', b'')
test(-1, 1, -1, b'', b'', b'', b'c', b'dc', b'edc')
test(-1, 1, 1, b'', b'a', b'', b'', b'', b'')

test(0, None, None, b'', b'a', b'ab', b'abc', b'abcd', b'abcde')
test(0, None, -1, b'', b'a', b'a', b'a', b'a', b'a')
test(0, None, 1, b'', b'a', b'ab', b'abc', b'abcd', b'abcde')
test(0, -1, None, b'', b'', b'a', b'ab', b'abc', b'abcd')
test(0, -1, -1, b'', b'', b'', b'', b'', b'')
test(0, -1, 1, b'', b'', b'a', b'ab', b'abc', b'abcd')
test(0, 0, None, b'', b'', b'', b'', b'', b'')
test(0, 0, -1, b'', b'', b'', b'', b'', b'')
test(0, 0, 1, b'', b'', b'', b'', b'', b'')
test(0, 1, None, b'', b'a', b'a', b'a', b'a', b'a')
test(0, 1, -1, b'', b'', b'', b'', b'', b'')
test(0, 1, 1, b'', b'a', b'a', b'a', b'a', b'a')

test(1, None, None, b'', b'', b'b', b'bc', b'bcd', b'bcde')
test(1, None, -1, b'', b'a', b'ba', b'ba', b'ba', b'ba')
test(1, None, 1, b'', b'', b'b', b'bc', b'bcd', b'bcde')
test(1, -1, None, b'', b'', b'', b'b', b'bc', b'bcd')
test(1, -1, -1, b'', b'', b'', b'', b'', b'')
test(1, -1, 1, b'', b'', b'', b'b', b'bc', b'bcd')
test(1, 0, None, b'', b'', b'', b'', b'', b'')
test(1, 0, -1, b'', b'', b'b', b'b', b'b', b'b')
test(1, 0, 1, b'', b'', b'', b'', b'', b'')
test(1, 1, None, b'', b'', b'', b'', b'', b'')
test(1, 1, -1, b'', b'', b'', b'', b'', b'')
test(1, 1, 1, b'', b'', b'', b'', b'', b'')


assert_fail('''b'abc'[True:]''')
assert_fail('''b'abc'[:True:]''')
assert_fail('''b'abc'[::True]''')
assert_fail('''b'abc'[::0]''')

