# No arguments.
assert_fail('''b''.find()''')

# One argument.
assert_fail('''b''.find(())''')

assert_eq(b'banana'.find(b''), 0)
assert_eq(b'banana'.find(b'an'), 1)
assert_eq(b'banana'.find(b'ban'), 0)
assert_eq(b'banana'.find(b'bb'), -1)
assert_eq(b'banana'.find(97), 1)

# Two arguments.
assert_fail('''b'banana'.find(b'', False)''')

assert_eq(b'abab'.find(b'ab', -5), 0)
assert_eq(b'abab'.find(b'ab', -4), 0)
assert_eq(b'abab'.find(b'ab', -3), 2)
assert_eq(b'abab'.find(b'ab', -2), 2)
assert_eq(b'abab'.find(b'ab', -1), -1)
assert_eq(b'abab'.find(b'ab', 0), 0)
assert_eq(b'abab'.find(b'ab', 1), 2)
assert_eq(b'abab'.find(b'ab', 2), 2)
assert_eq(b'abab'.find(b'ab', 3), -1)
assert_eq(b'abab'.find(b'ab', 4), -1)
assert_eq(b'abab'.find(b'ab', 5), -1)


# Three arguments.
assert_eq(b''.find(b'', -1, -1), 0)
assert_eq(b''.find(b'', -1, 0), 0)
assert_eq(b''.find(b'', -1, 1), 0)
assert_eq(b''.find(b'', 0, -1), 0)
assert_eq(b''.find(b'', 0, 0), 0)
assert_eq(b''.find(b'', 0, 1), 0)
assert_eq(b''.find(b'', 1, -1), -1)
assert_eq(b''.find(b'', 1, 0), -1)
assert_eq(b''.find(b'', 1, 1), -1)
assert_eq(b'abab'.find(b'ab', -5, -5), -1)
assert_eq(b'abab'.find(b'ab', -5, -4), -1)
assert_eq(b'abab'.find(b'ab', -5, -3), -1)
assert_eq(b'abab'.find(b'ab', -5, -2), 0)
assert_eq(b'abab'.find(b'ab', -5, -1), 0)
assert_eq(b'abab'.find(b'ab', -5, 0), -1)
assert_eq(b'abab'.find(b'ab', -5, 1), -1)
assert_eq(b'abab'.find(b'ab', -5, 2), 0)
assert_eq(b'abab'.find(b'ab', -5, 3), 0)
assert_eq(b'abab'.find(b'ab', -5, 4), 0)
assert_eq(b'abab'.find(b'ab', -5, 5), 0)
assert_eq(b'abab'.find(b'ab', -4, -5), -1)
assert_eq(b'abab'.find(b'ab', -4, -4), -1)
assert_eq(b'abab'.find(b'ab', -4, -3), -1)
assert_eq(b'abab'.find(b'ab', -4, -2), 0)
assert_eq(b'abab'.find(b'ab', -4, -1), 0)
assert_eq(b'abab'.find(b'ab', -4, 0), -1)
assert_eq(b'abab'.find(b'ab', -4, 1), -1)
assert_eq(b'abab'.find(b'ab', -4, 2), 0)
assert_eq(b'abab'.find(b'ab', -4, 3), 0)
assert_eq(b'abab'.find(b'ab', -4, 4), 0)
assert_eq(b'abab'.find(b'ab', -4, 5), 0)
assert_eq(b'abab'.find(b'ab', -3, -5), -1)
assert_eq(b'abab'.find(b'ab', -3, -4), -1)
assert_eq(b'abab'.find(b'ab', -3, -3), -1)
assert_eq(b'abab'.find(b'ab', -3, -2), -1)
assert_eq(b'abab'.find(b'ab', -3, -1), -1)
assert_eq(b'abab'.find(b'ab', -3, 0), -1)
assert_eq(b'abab'.find(b'ab', -3, 1), -1)
assert_eq(b'abab'.find(b'ab', -3, 2), -1)
assert_eq(b'abab'.find(b'ab', -3, 3), -1)
assert_eq(b'abab'.find(b'ab', -3, 4), 2)
assert_eq(b'abab'.find(b'ab', -3, 5), 2)
assert_eq(b'abab'.find(b'ab', -2, -5), -1)
assert_eq(b'abab'.find(b'ab', -2, -4), -1)
assert_eq(b'abab'.find(b'ab', -2, -3), -1)
assert_eq(b'abab'.find(b'ab', -2, -2), -1)
assert_eq(b'abab'.find(b'ab', -2, -1), -1)
assert_eq(b'abab'.find(b'ab', -2, 0), -1)
assert_eq(b'abab'.find(b'ab', -2, 1), -1)
assert_eq(b'abab'.find(b'ab', -2, 2), -1)
assert_eq(b'abab'.find(b'ab', -2, 3), -1)
assert_eq(b'abab'.find(b'ab', -2, 4), 2)
assert_eq(b'abab'.find(b'ab', -2, 5), 2)
assert_eq(b'abab'.find(b'ab', -1, -5), -1)
assert_eq(b'abab'.find(b'ab', -1, -4), -1)
assert_eq(b'abab'.find(b'ab', -1, -3), -1)
assert_eq(b'abab'.find(b'ab', -1, -2), -1)
assert_eq(b'abab'.find(b'ab', -1, -1), -1)
assert_eq(b'abab'.find(b'ab', -1, 0), -1)
assert_eq(b'abab'.find(b'ab', -1, 1), -1)
assert_eq(b'abab'.find(b'ab', -1, 2), -1)
assert_eq(b'abab'.find(b'ab', -1, 3), -1)
assert_eq(b'abab'.find(b'ab', -1, 4), -1)
assert_eq(b'abab'.find(b'ab', -1, 5), -1)
assert_eq(b'abab'.find(b'ab', 0, -5), -1)
assert_eq(b'abab'.find(b'ab', 0, -4), -1)
assert_eq(b'abab'.find(b'ab', 0, -3), -1)
assert_eq(b'abab'.find(b'ab', 0, -2), 0)
assert_eq(b'abab'.find(b'ab', 0, -1), 0)
assert_eq(b'abab'.find(b'ab', 0, 0), -1)
assert_eq(b'abab'.find(b'ab', 0, 1), -1)
assert_eq(b'abab'.find(b'ab', 0, 2), 0)
assert_eq(b'abab'.find(b'ab', 0, 3), 0)
assert_eq(b'abab'.find(b'ab', 0, 4), 0)
assert_eq(b'abab'.find(b'ab', 0, 5), 0)
assert_eq(b'abab'.find(b'ab', 1, -5), -1)
assert_eq(b'abab'.find(b'ab', 1, -4), -1)
assert_eq(b'abab'.find(b'ab', 1, -3), -1)
assert_eq(b'abab'.find(b'ab', 1, -2), -1)
assert_eq(b'abab'.find(b'ab', 1, -1), -1)
assert_eq(b'abab'.find(b'ab', 1, 0), -1)
assert_eq(b'abab'.find(b'ab', 1, 1), -1)
assert_eq(b'abab'.find(b'ab', 1, 2), -1)
assert_eq(b'abab'.find(b'ab', 1, 3), -1)
assert_eq(b'abab'.find(b'ab', 1, 4), 2)
assert_eq(b'abab'.find(b'ab', 1, 5), 2)
assert_eq(b'abab'.find(b'ab', 2, -5), -1)
assert_eq(b'abab'.find(b'ab', 2, -4), -1)
assert_eq(b'abab'.find(b'ab', 2, -3), -1)
assert_eq(b'abab'.find(b'ab', 2, -2), -1)
assert_eq(b'abab'.find(b'ab', 2, -1), -1)
assert_eq(b'abab'.find(b'ab', 2, 0), -1)
assert_eq(b'abab'.find(b'ab', 2, 1), -1)
assert_eq(b'abab'.find(b'ab', 2, 2), -1)
assert_eq(b'abab'.find(b'ab', 2, 3), -1)
assert_eq(b'abab'.find(b'ab', 2, 4), 2)
assert_eq(b'abab'.find(b'ab', 2, 5), 2)
assert_eq(b'abab'.find(b'ab', 3, -5), -1)
assert_eq(b'abab'.find(b'ab', 3, -4), -1)
assert_eq(b'abab'.find(b'ab', 3, -3), -1)
assert_eq(b'abab'.find(b'ab', 3, -2), -1)
assert_eq(b'abab'.find(b'ab', 3, -1), -1)
assert_eq(b'abab'.find(b'ab', 3, 0), -1)
assert_eq(b'abab'.find(b'ab', 3, 1), -1)
assert_eq(b'abab'.find(b'ab', 3, 2), -1)
assert_eq(b'abab'.find(b'ab', 3, 3), -1)
assert_eq(b'abab'.find(b'ab', 3, 4), -1)
assert_eq(b'abab'.find(b'ab', 3, 5), -1)
assert_eq(b'abab'.find(b'ab', 4, -5), -1)
assert_eq(b'abab'.find(b'ab', 4, -4), -1)
assert_eq(b'abab'.find(b'ab', 4, -3), -1)
assert_eq(b'abab'.find(b'ab', 4, -2), -1)
assert_eq(b'abab'.find(b'ab', 4, -1), -1)
assert_eq(b'abab'.find(b'ab', 4, 0), -1)
assert_eq(b'abab'.find(b'ab', 4, 1), -1)
assert_eq(b'abab'.find(b'ab', 4, 2), -1)
assert_eq(b'abab'.find(b'ab', 4, 3), -1)
assert_eq(b'abab'.find(b'ab', 4, 4), -1)
assert_eq(b'abab'.find(b'ab', 4, 5), -1)
assert_eq(b'abab'.find(b'ab', 5, -5), -1)
assert_eq(b'abab'.find(b'ab', 5, -4), -1)
assert_eq(b'abab'.find(b'ab', 5, -3), -1)
assert_eq(b'abab'.find(b'ab', 5, -2), -1)
assert_eq(b'abab'.find(b'ab', 5, -1), -1)
assert_eq(b'abab'.find(b'ab', 5, 0), -1)
assert_eq(b'abab'.find(b'ab', 5, 1), -1)
assert_eq(b'abab'.find(b'ab', 5, 2), -1)
assert_eq(b'abab'.find(b'ab', 5, 3), -1)
assert_eq(b'abab'.find(b'ab', 5, 4), -1)
assert_eq(b'abab'.find(b'ab', 5, 5), -1)

# Four arguments.
assert_fail('''b'abc'.find(b'', 0, 0, 0)''')


# Named arguments.
assert_fail('''b'abc'.find(sub = b'')''')
assert_fail('''b'abc'.find(b'', start = 0)''')
assert_fail('''b'abc'.find(b'', 0, end = 0)''')

