# No arguments.

assert_eq(b''.split(), [])
assert_eq(b'  '.split(), [])
assert_eq(b'abc'.split(), [b'abc'])
assert_eq(b'  abc  '.split(), [b'abc'])
assert_eq(b'  a  b  c  '.split(), [b'a', b'b', b'c'])
assert_eq(b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'.split(), [b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'])

assert_eq(b''.rsplit(), [])
assert_eq(b'  '.rsplit(), [])
assert_eq(b'abc'.rsplit(), [b'abc'])
assert_eq(b'  abc  '.rsplit(), [b'abc'])
assert_eq(b'  a  b  c  '.rsplit(), [b'a', b'b', b'c'])
assert_eq(b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'.rsplit(), [b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'])


# One argument.

assert_eq(b''.split(None), [])
assert_eq(b'  '.split(None), [])
assert_eq(b'abc'.split(None), [b'abc'])
assert_eq(b'  abc  '.split(None), [b'abc'])
assert_eq(b'  a  b  c  '.split(None), [b'a', b'b', b'c'])
assert_eq(b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'.split(None), [b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'])

assert_eq(b''.rsplit(None), [])
assert_eq(b'  '.rsplit(None), [])
assert_eq(b'abc'.rsplit(None), [b'abc'])
assert_eq(b'  abc  '.rsplit(None), [b'abc'])
assert_eq(b'  a  b  c  '.rsplit(None), [b'a', b'b', b'c'])
assert_eq(b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'.rsplit(None), [b'\xe2\x80\x82a\xe2\x80\x82b\xe2\x80\x82c\xe2\x80\x82'])

assert_fail('''b'abc'.split(True)''')
assert_fail('''b'abc'.rsplit(True)''')
assert_fail('''b'abc'.split(98)''')
assert_fail('''b'abc'.rsplit(98)''')
assert_fail('''b'abc'.split(b'')''')
assert_fail('''b'abc'.rsplit(b'')''')

assert_eq(b''.split(b'x'), [b''])
assert_eq(b'  '.split(b'x'), [b'  '])
assert_eq(b'axbxc'.split(b'x'), [b'a', b'b', b'c'])
assert_eq(b'xaxbxcx'.split(b'x'), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xxaxxbxxcxx'.split(b'x'), [b'', b'', b'a', b'', b'b', b'', b'c', b'', b''])
assert_eq(b'xxaxxbxxcxx'.split(b'xx'), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xaxbxcx'.split(b'xx'), [b'xaxbxcx'])

assert_eq(b''.rsplit(b'x'), [b''])
assert_eq(b'  '.rsplit(b'x'), [b'  '])
assert_eq(b'axbxc'.rsplit(b'x'), [b'a', b'b', b'c'])
assert_eq(b'xaxbxcx'.rsplit(b'x'), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'x'), [b'', b'', b'a', b'', b'b', b'', b'c', b'', b''])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'xx'), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xaxbxcx'.rsplit(b'xx'), [b'xaxbxcx'])


# Two arguments.

assert_eq(b''.split(b'x', -1), [b''])
assert_eq(b''.split(b'x', 0), [b''])
assert_eq(b''.split(b'x', 1), [b''])
assert_eq(b'  '.split(b'x', -1), [b'  '])
assert_eq(b'  '.split(b'x', 0), [b'  '])
assert_eq(b'  '.split(b'x', 1), [b'  '])
assert_eq(b'axbxc'.split(b'x', -1), [b'a', b'b', b'c'])
assert_eq(b'axbxc'.split(b'x', 0), [b'axbxc'])
assert_eq(b'axbxc'.split(b'x', 1), [b'a', b'bxc'])
assert_eq(b'xaxbxcx'.split(b'x', -1), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xaxbxcx'.split(b'x', 0), [b'xaxbxcx'])
assert_eq(b'xaxbxcx'.split(b'x', 1), [b'', b'axbxcx'])
assert_eq(b'xxaxxbxxcxx'.split(b'x', -1), [b'', b'', b'a', b'', b'b', b'', b'c', b'', b''])
assert_eq(b'xxaxxbxxcxx'.split(b'x', 0), [b'xxaxxbxxcxx'])
assert_eq(b'xxaxxbxxcxx'.split(b'x', 1), [b'', b'xaxxbxxcxx'])
assert_eq(b'xxaxxbxxcxx'.split(b'xx', -1), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xxaxxbxxcxx'.split(b'xx', 0), [b'xxaxxbxxcxx'])
assert_eq(b'xxaxxbxxcxx'.split(b'xx', 1), [b'', b'axxbxxcxx'])
assert_eq(b'xaxbxcx'.split(b'xx', -1), [b'xaxbxcx'])
assert_eq(b'xaxbxcx'.split(b'xx', 0), [b'xaxbxcx'])
assert_eq(b'xaxbxcx'.split(b'xx', 1), [b'xaxbxcx'])

assert_eq(b''.rsplit(b'x', -1), [b''])
assert_eq(b''.rsplit(b'x', 0), [b''])
assert_eq(b''.rsplit(b'x', 1), [b''])
assert_eq(b'  '.rsplit(b'x', -1), [b'  '])
assert_eq(b'  '.rsplit(b'x', 0), [b'  '])
assert_eq(b'  '.rsplit(b'x', 1), [b'  '])
assert_eq(b'axbxc'.rsplit(b'x', -1), [b'a', b'b', b'c'])
assert_eq(b'axbxc'.rsplit(b'x', 0), [b'axbxc'])
assert_eq(b'axbxc'.rsplit(b'x', 1), [b'axb', b'c'])
assert_eq(b'xaxbxcx'.rsplit(b'x', -1), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xaxbxcx'.rsplit(b'x', 0), [b'xaxbxcx'])
assert_eq(b'xaxbxcx'.rsplit(b'x', 1), [b'xaxbxc', b''])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'x', -1), [b'', b'', b'a', b'', b'b', b'', b'c', b'', b''])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'x', 0), [b'xxaxxbxxcxx'])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'x', 1), [b'xxaxxbxxcx', b''])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'xx', -1), [b'', b'a', b'b', b'c', b''])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'xx', 0), [b'xxaxxbxxcxx'])
assert_eq(b'xxaxxbxxcxx'.rsplit(b'xx', 1), [b'xxaxxbxxc', b''])
assert_eq(b'xaxbxcx'.rsplit(b'xx', -1), [b'xaxbxcx'])
assert_eq(b'xaxbxcx'.rsplit(b'xx', 0), [b'xaxbxcx'])
assert_eq(b'xaxbxcx'.rsplit(b'xx', 1), [b'xaxbxcx'])


assert_fail('''b'abc'.split(b'', 0)''')
assert_fail('''b'abc'.rsplit(b'', 0)''')
assert_fail('''b'abc'.split(False, 0)''')
assert_fail('''b'abc'.rsplit(False, 0)''')
assert_fail('''b'abc'.split(b'b', False)''')
assert_fail('''b'abc'.rsplit(b'b', False)''')
assert_fail('''b'abc'.split(None, False)''')
assert_fail('''b'abc'.rsplit(None, False)''')
assert_fail('''b'abc'.split(b'b', None)''')
assert_fail('''b'abc'.rsplit(b'b', None)''')

assert_eq(b''.split(None, -1), [])
assert_eq(b''.split(None, 0), [])
assert_eq(b''.split(None, 1), [])
assert_eq(b'  '.split(None, -1), [])
assert_eq(b'  '.split(None, 0), [])
assert_eq(b'  '.split(None, 1), [])
assert_eq(b'abc'.split(None, -1), [b'abc'])
assert_eq(b'abc'.split(None, 0), [b'abc'])
assert_eq(b'abc'.split(None, 1), [b'abc'])
assert_eq(b'  abc  '.split(None, -1), [b'abc'])
assert_eq(b'  abc  '.split(None, 0), [b'abc  '])
assert_eq(b'  abc  '.split(None, 1), [b'abc'])
assert_eq(b'  a  b  c  '.split(None, -1), [b'a', b'b', b'c'])
assert_eq(b'  a  b  c  '.split(None, 0), [b'a  b  c  '])
assert_eq(b'  a  b  c  '.split(None, 1), [b'a', b'b  c  '])

assert_eq(b''.rsplit(None, -1), [])
assert_eq(b''.rsplit(None, 0), [])
assert_eq(b''.rsplit(None, 1), [])
assert_eq(b'  '.rsplit(None, -1), [])
assert_eq(b'  '.rsplit(None, 0), [])
assert_eq(b'  '.rsplit(None, 1), [])
assert_eq(b'abc'.rsplit(None, -1), [b'abc'])
assert_eq(b'abc'.rsplit(None, 0), [b'abc'])
assert_eq(b'abc'.rsplit(None, 1), [b'abc'])
assert_eq(b'  abc  '.rsplit(None, -1), [b'abc'])
assert_eq(b'  abc  '.rsplit(None, 0), [b'  abc'])
assert_eq(b'  abc  '.rsplit(None, 1), [b'abc'])
assert_eq(b'  a  b  c  '.rsplit(None, -1), [b'a', b'b', b'c'])
assert_eq(b'  a  b  c  '.rsplit(None, 0), [b'  a  b  c'])
assert_eq(b'  a  b  c  '.rsplit(None, 1), [b'  a  b', b'c'])


# Three arguments.
assert_fail('''b'abc'.split(None, 0, None)''')
assert_fail('''b'abc'.rsplit(None, 0, None)''')


# Named arguemnts.

assert_eq(b'abc'.split(b'b', maxsplit = -1), [b'a', b'c'])
assert_eq(b'abc'.rsplit(b'b', maxsplit = -1), [b'a', b'c'])
assert_eq(b'abc'.split(sep = b'b', maxsplit = -1), [b'a', b'c'])
assert_eq(b'abc'.rsplit(sep = b'b', maxsplit = -1), [b'a', b'c'])

assert_fail('''b'abc'.split(b'b', sep = b'b')''')
assert_fail('''b'abc'.rsplit(b'b', sep = b'b')''')
assert_fail('''b'abc'.split(b'b', -1, maxsplit = -1)''')
assert_fail('''b'abc'.rsplit(b'b', -1, maxsplit = -1))''')
assert_fail('''b'abc'.split(b'b', other = None)''')
assert_fail('''b'abc'.rsplit(b'b', other = None)''')

