assert_true(b'' in b'')
assert_true(b'' in b'a')
assert_true(b'a' in b'a')
assert_true(b'a' in b'aaa')
assert_true(b'aa' in b'aaa')
assert_false(b'b' in b'aaa')
assert_true(b'b' in b'aba')
assert_true(97 in b'aba')
assert_true(98 in b'aba')
assert_false(99 in b'aba')

assert_fail('''"" in b'' ''')
assert_fail('''1.0 in b'' ''')
assert_fail('''-1 in b'' ''')
assert_fail('''256 in b'' ''')
assert_fail('''(1<<64) in b'' ''')
