assert_true(b'' in b'')
assert_false(b'' not in b'')
assert_true(b'' in b'a')
assert_false(b'' not in b'a')
assert_true(b'a' in b'a')
assert_false(b'a' not in b'a')
assert_true(b'a' in b'aaa')
assert_false(b'a' not in b'aaa')
assert_true(b'aa' in b'aaa')
assert_false(b'aa' not in b'aaa')
assert_false(b'b' in b'aaa')
assert_true(b'b' not in b'aaa')
assert_true(b'b' in b'aba')
assert_false(b'b' not in b'aba')
assert_true(97 in b'aba')
assert_false(97 not in b'aba')
assert_true(98 in b'aba')
assert_false(98 not in b'aba')
assert_false(99 in b'aba')
assert_true(99 not in b'aba')

assert_fail('''"" in b'' ''')
assert_fail('''"" not in b'' ''')
assert_fail('''1.0 in b'' ''')
assert_fail('''1.0 not in b'' ''')
assert_fail('''-1 in b'' ''')
assert_fail('''-1 not in b'' ''')
assert_fail('''256 in b'' ''')
assert_fail('''256 not in b'' ''')
assert_fail('''(1<<64) in b'' ''')
assert_fail('''(1<<64) not in b'' ''')
