# No arguments.
assert_fail('''
b'abc'.count()
''')

# One argument.
## Empty bytes as parameter.
assert_eq(b''.count(b''), 1)
assert_eq(b'abc'.count(b''), 4)

assert_eq(b'banana'.count(b'a'), 3)
assert_eq(b'aaaaaa'.count(b'aa'), 3)
assert_eq(b'banana'.count(97), 3)
assert_fail('''b'banana'.count(-1)''')
assert_fail('''b'banana'.count(256)''')
assert_fail('''b'banana'.count(-1 << 64)''')
assert_fail('''b'banana'.count(1 << 64)''')
assert_fail('''b'banana'.count(None)''')
assert_fail('''b'banana'.count(97.0)''')
assert_fail('''b'banana'.count((97,))''')

# Two arguments.
## Empty bytes as parameter.
assert_eq(b''.count(b'', -1, -1), 1)
assert_eq(b''.count(b'', -1, 0), 1)
assert_eq(b''.count(b'', -1, 1), 1)
assert_eq(b''.count(b'', 0, -1), 1)
assert_eq(b''.count(b'', 0, 0), 1)
assert_eq(b''.count(b'', 0, 1), 1)
assert_eq(b''.count(b'', 1, -1), 0)
assert_eq(b''.count(b'', 1, 0), 0)
assert_eq(b''.count(b'', 1, 1), 0)

assert_eq(b'abc'.count(b'', -4, -4), 1)
assert_eq(b'abc'.count(b'', -4, -3), 1)
assert_eq(b'abc'.count(b'', -4, -2), 2)
assert_eq(b'abc'.count(b'', -4, -1), 3)
assert_eq(b'abc'.count(b'', -4, 0), 1)
assert_eq(b'abc'.count(b'', -4, 1), 2)
assert_eq(b'abc'.count(b'', -4, 2), 3)
assert_eq(b'abc'.count(b'', -4, 3), 4)
assert_eq(b'abc'.count(b'', -4, 4), 4)
assert_eq(b'abc'.count(b'', -3, -4), 1)
assert_eq(b'abc'.count(b'', -3, -3), 1)
assert_eq(b'abc'.count(b'', -3, -2), 2)
assert_eq(b'abc'.count(b'', -3, -1), 3)
assert_eq(b'abc'.count(b'', -3, 0), 1)
assert_eq(b'abc'.count(b'', -3, 1), 2)
assert_eq(b'abc'.count(b'', -3, 2), 3)
assert_eq(b'abc'.count(b'', -3, 3), 4)
assert_eq(b'abc'.count(b'', -3, 4), 4)
assert_eq(b'abc'.count(b'', -2, -4), 0)
assert_eq(b'abc'.count(b'', -2, -3), 0)
assert_eq(b'abc'.count(b'', -2, -2), 1)
assert_eq(b'abc'.count(b'', -2, -1), 2)
assert_eq(b'abc'.count(b'', -2, 0), 0)
assert_eq(b'abc'.count(b'', -2, 1), 1)
assert_eq(b'abc'.count(b'', -2, 2), 2)
assert_eq(b'abc'.count(b'', -2, 3), 3)
assert_eq(b'abc'.count(b'', -2, 4), 3)
assert_eq(b'abc'.count(b'', -1, -4), 0)
assert_eq(b'abc'.count(b'', -1, -3), 0)
assert_eq(b'abc'.count(b'', -1, -2), 0)
assert_eq(b'abc'.count(b'', -1, -1), 1)
assert_eq(b'abc'.count(b'', -1, 0), 0)
assert_eq(b'abc'.count(b'', -1, 1), 0)
assert_eq(b'abc'.count(b'', -1, 2), 1)
assert_eq(b'abc'.count(b'', -1, 3), 2)
assert_eq(b'abc'.count(b'', -1, 4), 2)
assert_eq(b'abc'.count(b'', 0, -4), 1)
assert_eq(b'abc'.count(b'', 0, -3), 1)
assert_eq(b'abc'.count(b'', 0, -2), 2)
assert_eq(b'abc'.count(b'', 0, -1), 3)
assert_eq(b'abc'.count(b'', 0, 0), 1)
assert_eq(b'abc'.count(b'', 0, 1), 2)
assert_eq(b'abc'.count(b'', 0, 2), 3)
assert_eq(b'abc'.count(b'', 0, 3), 4)
assert_eq(b'abc'.count(b'', 0, 4), 4)
assert_eq(b'abc'.count(b'', 1, -4), 0)
assert_eq(b'abc'.count(b'', 1, -3), 0)
assert_eq(b'abc'.count(b'', 1, -2), 1)
assert_eq(b'abc'.count(b'', 1, -1), 2)
assert_eq(b'abc'.count(b'', 1, 0), 0)
assert_eq(b'abc'.count(b'', 1, 1), 1)
assert_eq(b'abc'.count(b'', 1, 2), 2)
assert_eq(b'abc'.count(b'', 1, 3), 3)
assert_eq(b'abc'.count(b'', 1, 4), 3)
assert_eq(b'abc'.count(b'', 2, -4), 0)
assert_eq(b'abc'.count(b'', 2, -3), 0)
assert_eq(b'abc'.count(b'', 2, -2), 0)
assert_eq(b'abc'.count(b'', 2, -1), 1)
assert_eq(b'abc'.count(b'', 2, 0), 0)
assert_eq(b'abc'.count(b'', 2, 1), 0)
assert_eq(b'abc'.count(b'', 2, 2), 1)
assert_eq(b'abc'.count(b'', 2, 3), 2)
assert_eq(b'abc'.count(b'', 2, 4), 2)
assert_eq(b'abc'.count(b'', 3, -4), 0)
assert_eq(b'abc'.count(b'', 3, -3), 0)
assert_eq(b'abc'.count(b'', 3, -2), 0)
assert_eq(b'abc'.count(b'', 3, -1), 0)
assert_eq(b'abc'.count(b'', 3, 0), 0)
assert_eq(b'abc'.count(b'', 3, 1), 0)
assert_eq(b'abc'.count(b'', 3, 2), 0)
assert_eq(b'abc'.count(b'', 3, 3), 1)
assert_eq(b'abc'.count(b'', 3, 4), 1)
assert_eq(b'abc'.count(b'', 4, -4), 0)
assert_eq(b'abc'.count(b'', 4, -3), 0)
assert_eq(b'abc'.count(b'', 4, -2), 0)
assert_eq(b'abc'.count(b'', 4, -1), 0)
assert_eq(b'abc'.count(b'', 4, 0), 0)
assert_eq(b'abc'.count(b'', 4, 1), 0)
assert_eq(b'abc'.count(b'', 4, 2), 0)
assert_eq(b'abc'.count(b'', 4, 3), 0)
assert_eq(b'abc'.count(b'', 4, 4), 0)

assert_eq(b'banana'.count(b'b', 0), 1)
assert_eq(b'banana'.count(b'b', 1), 0)
assert_eq(b'banana'.count(b'a', -10), 3)
assert_eq(b'banana'.count(b'a', -1), 1)
assert_eq(b'banana'.count(b'a', 0), 3)
assert_eq(b'banana'.count(b'a', 1), 3)
assert_eq(b'banana'.count(b'a', 2), 2)
assert_eq(b'banana'.count(b'a', 10), 0)
assert_eq(b'banana'.count(b'b', None), 1)
assert_eq(b'banana'.count(b'a', None), 3)
assert_fail('''b'banana'.count(b'a', False)''')

assert_eq(b'banana'.count(b'a', 0, 100), 3)
assert_eq(b'banana'.count(b'a', 0, -1), 2)
assert_eq(b'banana'.count(b'a', None, None), 3)
assert_fail('''b'banana'.count(b'a', None, False)''')
assert_fail('''b'banana'.count(b'a', 0, 0, 0)''')
assert_fail('''b'banana'.count(b'a', start = 0)''')
assert_fail('''b'banana'.count(b'a', 0, end = 0)''')

