assert_true(not None)
assert_false(True if None else False)
assert_succeed("{None: None}")
assert_eq(str(None), "None")
assert_ne(None, 0)
assert_ne(None, 1)
assert_ne(None, False)
assert_ne(None, True)
assert_ne(None, "")
assert_ne(None, b"")
assert_ne(None, [])
assert_ne(None, ())
assert_ne(None, {})
assert_ne(None, set())
assert_ne(None, [].append)
assert_ne(None, range(0))
