a = set()
b = set([0])
c = set([0])
d = set([1])
e = set([0, 1])

assert_true(a == a)
assert_false(a != a)
assert_false(a == b)
assert_true(a != b)
assert_false(a == c)
assert_true(a != c)
assert_false(a == d)
assert_true(a != d)
assert_false(a == e)
assert_true(a != e)

assert_false(b == a)
assert_true(b != a)
assert_true(b == b)
assert_false(b != b)
assert_true(b == c)
assert_false(b != c)
assert_false(b == d)
assert_true(b != d)
assert_false(b == e)
assert_true(b != e)

assert_false(c == a)
assert_true(c != a)
assert_true(c == b)
assert_false(c != b)
assert_true(c == c)
assert_false(c != c)
assert_false(c == d)
assert_true(c != d)
assert_false(c == e)
assert_true(c != e)

assert_false(d == a)
assert_true(d != a)
assert_false(d == b)
assert_true(d != b)
assert_false(d == c)
assert_true(d != c)
assert_true(d == d)
assert_false(d != d)
assert_false(d == e)
assert_true(d != e)

assert_false(e == a)
assert_true(e != a)
assert_false(e == b)
assert_true(e != b)
assert_false(e == c)
assert_true(e != c)
assert_false(e == d)
assert_true(e != d)
assert_true(e == e)
assert_false(e != e)


assert_true(set([0, 1, 2, 3]) == set([3, 2, 1, 0]))

