assert_false("".isalpha())
assert_false(" ".isalpha())
assert_true("abc".isalpha())
assert_false("123".isalpha())
assert_false("abc123".isalpha())
assert_false("abc123!@#".isalpha())
assert_true("LettersOnly".isalpha())
assert_false("Letters and spaces".isalpha())
assert_true("µ".isalpha())
assert_false("¼".isalpha())
assert_true("\u3405".isalpha())
assert_fail('''"".isalpha(1)''')
assert_fail('''"".isalpha(name = 1)''')
