assert_fail("""'abc'.find()""")
assert_fail("""'abc'.find(())""")
assert_fail("""'abc'.rfind()""")
assert_fail("""'abc'.rfind(())""")

assert_eq("banana".find(""), 0)
assert_eq("banana".find("an"), 1)
assert_eq("banana".find("ban"), 0)
assert_eq("banana".find("bb"), -1)
assert_eq("banana".rfind(""), 6)
assert_eq("banana".rfind("an"), 3)
assert_eq("banana".rfind("ban"), 0)
assert_eq("banana".rfind("bb"), -1)

assert_fail("""'banana'.find('an', True)""")
assert_fail("""'banana'.rfind('an', True)""")

assert_eq("abab".find("ab", -5), 0)
assert_eq("abab".find("ab", -4), 0)
assert_eq("abab".find("ab", -3), 2)
assert_eq("abab".find("ab", -2), 2)
assert_eq("abab".find("ab", -1), -1)
assert_eq("abab".find("ab", 0), 0)
assert_eq("abab".find("ab", None), 0)
assert_eq("abab".find("ab", 1), 2)
assert_eq("abab".find("ab", 2), 2)
assert_eq("abab".find("ab", 3), -1)
assert_eq("abab".find("ab", 4), -1)
assert_eq("abab".find("ab", 5), -1)

assert_eq("abab".rfind("ab", -5), 2)
assert_eq("abab".rfind("ab", -4), 2)
assert_eq("abab".rfind("ab", -3), 2)
assert_eq("abab".rfind("ab", -2), 2)
assert_eq("abab".rfind("ab", -1), -1)
assert_eq("abab".rfind("ab", 0), 2)
assert_eq("abab".rfind("ab", None), 2)
assert_eq("abab".rfind("ab", 1), 2)
assert_eq("abab".rfind("ab", 2), 2)
assert_eq("abab".rfind("ab", 3), -1)
assert_eq("abab".rfind("ab", 4), -1)
assert_eq("abab".rfind("ab", 5), -1)


assert_eq("".find("", -1, -1), 0)
assert_eq("".find("", -1, 0), 0)
assert_eq("".find("", -1, None), 0)
assert_eq("".find("", -1, 1), 0)
assert_eq("".find("", 0, -1), 0)
assert_eq("".find("", None, -1), 0)
assert_eq("".find("", 0, 0), 0)
assert_eq("".find("", None, None), 0)
assert_eq("".find("", 0, 1), 0)
assert_eq("".find("", None, 1), 0)
assert_eq("".find("", 1, -1), -1)
assert_eq("".find("", 1, 0), -1)
assert_eq("".find("", 1, None), -1)
assert_eq("".find("", 1, 1), -1)

assert_eq("".rfind("", -1, -1), 0)
assert_eq("".rfind("", -1, 0), 0)
assert_eq("".rfind("", -1, None), 0)
assert_eq("".rfind("", -1, 1), 0)
assert_eq("".rfind("", 0, -1), 0)
assert_eq("".rfind("", None, -1), 0)
assert_eq("".rfind("", 0, 0), 0)
assert_eq("".rfind("", None, None), 0)
assert_eq("".rfind("", 0, 1), 0)
assert_eq("".rfind("", None, 1), 0)
assert_eq("".rfind("", 1, -1), -1)
assert_eq("".rfind("", 1, 0), -1)
assert_eq("".rfind("", 1, None), -1)
assert_eq("".rfind("", 1, 1), -1)


assert_eq("abab".find("ab", -5, -5), -1)
assert_eq("abab".find("ab", -5, -4), -1)
assert_eq("abab".find("ab", -5, -3), -1)
assert_eq("abab".find("ab", -5, -2), 0)
assert_eq("abab".find("ab", -5, -1), 0)
assert_eq("abab".find("ab", -5, 0), -1)
assert_eq("abab".find("ab", -5, None), 0)
assert_eq("abab".find("ab", -5, 1), -1)
assert_eq("abab".find("ab", -5, 2), 0)
assert_eq("abab".find("ab", -5, 3), 0)
assert_eq("abab".find("ab", -5, 4), 0)
assert_eq("abab".find("ab", -5, 5), 0)
assert_eq("abab".find("ab", -4, -5), -1)
assert_eq("abab".find("ab", -4, -4), -1)
assert_eq("abab".find("ab", -4, -3), -1)
assert_eq("abab".find("ab", -4, -2), 0)
assert_eq("abab".find("ab", -4, -1), 0)
assert_eq("abab".find("ab", -4, 0), -1)
assert_eq("abab".find("ab", -4, None), 0)
assert_eq("abab".find("ab", -4, 1), -1)
assert_eq("abab".find("ab", -4, 2), 0)
assert_eq("abab".find("ab", -4, 3), 0)
assert_eq("abab".find("ab", -4, 4), 0)
assert_eq("abab".find("ab", -4, 5), 0)
assert_eq("abab".find("ab", -3, -5), -1)
assert_eq("abab".find("ab", -3, -4), -1)
assert_eq("abab".find("ab", -3, -3), -1)
assert_eq("abab".find("ab", -3, -2), -1)
assert_eq("abab".find("ab", -3, -1), -1)
assert_eq("abab".find("ab", -3, 0), -1)
assert_eq("abab".find("ab", -3, None), 2)
assert_eq("abab".find("ab", -3, 1), -1)
assert_eq("abab".find("ab", -3, 2), -1)
assert_eq("abab".find("ab", -3, 3), -1)
assert_eq("abab".find("ab", -3, 4), 2)
assert_eq("abab".find("ab", -3, 5), 2)
assert_eq("abab".find("ab", -2, -5), -1)
assert_eq("abab".find("ab", -2, -4), -1)
assert_eq("abab".find("ab", -2, -3), -1)
assert_eq("abab".find("ab", -2, -2), -1)
assert_eq("abab".find("ab", -2, -1), -1)
assert_eq("abab".find("ab", -2, 0), -1)
assert_eq("abab".find("ab", -2, None), 2)
assert_eq("abab".find("ab", -2, 1), -1)
assert_eq("abab".find("ab", -2, 2), -1)
assert_eq("abab".find("ab", -2, 3), -1)
assert_eq("abab".find("ab", -2, 4), 2)
assert_eq("abab".find("ab", -2, 5), 2)
assert_eq("abab".find("ab", -1, -5), -1)
assert_eq("abab".find("ab", -1, -4), -1)
assert_eq("abab".find("ab", -1, -3), -1)
assert_eq("abab".find("ab", -1, -2), -1)
assert_eq("abab".find("ab", -1, -1), -1)
assert_eq("abab".find("ab", -1, 0), -1)
assert_eq("abab".find("ab", -1, None), -1)
assert_eq("abab".find("ab", -1, 1), -1)
assert_eq("abab".find("ab", -1, 2), -1)
assert_eq("abab".find("ab", -1, 3), -1)
assert_eq("abab".find("ab", -1, 4), -1)
assert_eq("abab".find("ab", -1, 5), -1)
assert_eq("abab".find("ab", 0, -5), -1)
assert_eq("abab".find("ab", None, -5), -1)
assert_eq("abab".find("ab", 0, -4), -1)
assert_eq("abab".find("ab", None, -4), -1)
assert_eq("abab".find("ab", 0, -3), -1)
assert_eq("abab".find("ab", None, -3), -1)
assert_eq("abab".find("ab", 0, -2), 0)
assert_eq("abab".find("ab", None, -2), 0)
assert_eq("abab".find("ab", 0, -1), 0)
assert_eq("abab".find("ab", None, -1), 0)
assert_eq("abab".find("ab", 0, 0), -1)
assert_eq("abab".find("ab", None, None), 0)
assert_eq("abab".find("ab", 0, 1), -1)
assert_eq("abab".find("ab", None, 1), -1)
assert_eq("abab".find("ab", 0, 2), 0)
assert_eq("abab".find("ab", None, 2), 0)
assert_eq("abab".find("ab", 0, 3), 0)
assert_eq("abab".find("ab", None, 3), 0)
assert_eq("abab".find("ab", 0, 4), 0)
assert_eq("abab".find("ab", None, 4), 0)
assert_eq("abab".find("ab", 0, 5), 0)
assert_eq("abab".find("ab", None, 5), 0)
assert_eq("abab".find("ab", 1, -5), -1)
assert_eq("abab".find("ab", 1, -4), -1)
assert_eq("abab".find("ab", 1, -3), -1)
assert_eq("abab".find("ab", 1, -2), -1)
assert_eq("abab".find("ab", 1, -1), -1)
assert_eq("abab".find("ab", 1, 0), -1)
assert_eq("abab".find("ab", 1, None), 2)
assert_eq("abab".find("ab", 1, 1), -1)
assert_eq("abab".find("ab", 1, 2), -1)
assert_eq("abab".find("ab", 1, 3), -1)
assert_eq("abab".find("ab", 1, 4), 2)
assert_eq("abab".find("ab", 1, 5), 2)
assert_eq("abab".find("ab", 2, -5), -1)
assert_eq("abab".find("ab", 2, -4), -1)
assert_eq("abab".find("ab", 2, -3), -1)
assert_eq("abab".find("ab", 2, -2), -1)
assert_eq("abab".find("ab", 2, -1), -1)
assert_eq("abab".find("ab", 2, 0), -1)
assert_eq("abab".find("ab", 2, None), 2)
assert_eq("abab".find("ab", 2, 1), -1)
assert_eq("abab".find("ab", 2, 2), -1)
assert_eq("abab".find("ab", 2, 3), -1)
assert_eq("abab".find("ab", 2, 4), 2)
assert_eq("abab".find("ab", 2, 5), 2)
assert_eq("abab".find("ab", 3, -5), -1)
assert_eq("abab".find("ab", 3, -4), -1)
assert_eq("abab".find("ab", 3, -3), -1)
assert_eq("abab".find("ab", 3, -2), -1)
assert_eq("abab".find("ab", 3, -1), -1)
assert_eq("abab".find("ab", 3, 0), -1)
assert_eq("abab".find("ab", 3, None), -1)
assert_eq("abab".find("ab", 3, 1), -1)
assert_eq("abab".find("ab", 3, 2), -1)
assert_eq("abab".find("ab", 3, 3), -1)
assert_eq("abab".find("ab", 3, 4), -1)
assert_eq("abab".find("ab", 3, 5), -1)
assert_eq("abab".find("ab", 4, -5), -1)
assert_eq("abab".find("ab", 4, -4), -1)
assert_eq("abab".find("ab", 4, -3), -1)
assert_eq("abab".find("ab", 4, -2), -1)
assert_eq("abab".find("ab", 4, -1), -1)
assert_eq("abab".find("ab", 4, 0), -1)
assert_eq("abab".find("ab", 4, None), -1)
assert_eq("abab".find("ab", 4, 1), -1)
assert_eq("abab".find("ab", 4, 2), -1)
assert_eq("abab".find("ab", 4, 3), -1)
assert_eq("abab".find("ab", 4, 4), -1)
assert_eq("abab".find("ab", 4, 5), -1)
assert_eq("abab".find("ab", 5, -5), -1)
assert_eq("abab".find("ab", 5, -4), -1)
assert_eq("abab".find("ab", 5, -3), -1)
assert_eq("abab".find("ab", 5, -2), -1)
assert_eq("abab".find("ab", 5, -1), -1)
assert_eq("abab".find("ab", 5, 0), -1)
assert_eq("abab".find("ab", 5, None), -1)
assert_eq("abab".find("ab", 5, 1), -1)
assert_eq("abab".find("ab", 5, 2), -1)
assert_eq("abab".find("ab", 5, 3), -1)
assert_eq("abab".find("ab", 5, 4), -1)
assert_eq("abab".find("ab", 5, 5), -1)

assert_eq("abab".rfind("ab", -5, -5), -1)
assert_eq("abab".rfind("ab", -5, -4), -1)
assert_eq("abab".rfind("ab", -5, -3), -1)
assert_eq("abab".rfind("ab", -5, -2), 0)
assert_eq("abab".rfind("ab", -5, -1), 0)
assert_eq("abab".rfind("ab", -5, 0), -1)
assert_eq("abab".rfind("ab", -5, None), 2)
assert_eq("abab".rfind("ab", -5, 1), -1)
assert_eq("abab".rfind("ab", -5, 2), 0)
assert_eq("abab".rfind("ab", -5, 3), 0)
assert_eq("abab".rfind("ab", -5, 4), 2)
assert_eq("abab".rfind("ab", -5, 5), 2)
assert_eq("abab".rfind("ab", -4, -5), -1)
assert_eq("abab".rfind("ab", -4, -4), -1)
assert_eq("abab".rfind("ab", -4, -3), -1)
assert_eq("abab".rfind("ab", -4, -2), 0)
assert_eq("abab".rfind("ab", -4, -1), 0)
assert_eq("abab".rfind("ab", -4, 0), -1)
assert_eq("abab".rfind("ab", -4, None), 2)
assert_eq("abab".rfind("ab", -4, 1), -1)
assert_eq("abab".rfind("ab", -4, 2), 0)
assert_eq("abab".rfind("ab", -4, 3), 0)
assert_eq("abab".rfind("ab", -4, 4), 2)
assert_eq("abab".rfind("ab", -4, 5), 2)
assert_eq("abab".rfind("ab", -3, -5), -1)
assert_eq("abab".rfind("ab", -3, -4), -1)
assert_eq("abab".rfind("ab", -3, -3), -1)
assert_eq("abab".rfind("ab", -3, -2), -1)
assert_eq("abab".rfind("ab", -3, -1), -1)
assert_eq("abab".rfind("ab", -3, 0), -1)
assert_eq("abab".rfind("ab", -3, None), 2)
assert_eq("abab".rfind("ab", -3, 1), -1)
assert_eq("abab".rfind("ab", -3, 2), -1)
assert_eq("abab".rfind("ab", -3, 3), -1)
assert_eq("abab".rfind("ab", -3, 4), 2)
assert_eq("abab".rfind("ab", -3, 5), 2)
assert_eq("abab".rfind("ab", -2, -5), -1)
assert_eq("abab".rfind("ab", -2, -4), -1)
assert_eq("abab".rfind("ab", -2, -3), -1)
assert_eq("abab".rfind("ab", -2, -2), -1)
assert_eq("abab".rfind("ab", -2, -1), -1)
assert_eq("abab".rfind("ab", -2, 0), -1)
assert_eq("abab".rfind("ab", -2, None), 2)
assert_eq("abab".rfind("ab", -2, 1), -1)
assert_eq("abab".rfind("ab", -2, 2), -1)
assert_eq("abab".rfind("ab", -2, 3), -1)
assert_eq("abab".rfind("ab", -2, 4), 2)
assert_eq("abab".rfind("ab", -2, 5), 2)
assert_eq("abab".rfind("ab", -1, -5), -1)
assert_eq("abab".rfind("ab", -1, -4), -1)
assert_eq("abab".rfind("ab", -1, -3), -1)
assert_eq("abab".rfind("ab", -1, -2), -1)
assert_eq("abab".rfind("ab", -1, -1), -1)
assert_eq("abab".rfind("ab", -1, 0), -1)
assert_eq("abab".rfind("ab", -1, None), -1)
assert_eq("abab".rfind("ab", -1, 1), -1)
assert_eq("abab".rfind("ab", -1, 2), -1)
assert_eq("abab".rfind("ab", -1, 3), -1)
assert_eq("abab".rfind("ab", -1, 4), -1)
assert_eq("abab".rfind("ab", -1, 5), -1)
assert_eq("abab".rfind("ab", 0, -5), -1)
assert_eq("abab".rfind("ab", None, -5), -1)
assert_eq("abab".rfind("ab", 0, -4), -1)
assert_eq("abab".rfind("ab", None, -4), -1)
assert_eq("abab".rfind("ab", 0, -3), -1)
assert_eq("abab".rfind("ab", None, -3), -1)
assert_eq("abab".rfind("ab", 0, -2), 0)
assert_eq("abab".rfind("ab", None, -2), 0)
assert_eq("abab".rfind("ab", 0, -1), 0)
assert_eq("abab".rfind("ab", None, -1), 0)
assert_eq("abab".rfind("ab", 0, 0), -1)
assert_eq("abab".rfind("ab", None, None), 2)
assert_eq("abab".rfind("ab", 0, 1), -1)
assert_eq("abab".rfind("ab", None, 1), -1)
assert_eq("abab".rfind("ab", 0, 2), 0)
assert_eq("abab".rfind("ab", None, 2), 0)
assert_eq("abab".rfind("ab", 0, 3), 0)
assert_eq("abab".rfind("ab", None, 3), 0)
assert_eq("abab".rfind("ab", 0, 4), 2)
assert_eq("abab".rfind("ab", None, 4), 2)
assert_eq("abab".rfind("ab", 0, 5), 2)
assert_eq("abab".rfind("ab", None, 5), 2)
assert_eq("abab".rfind("ab", 1, -5), -1)
assert_eq("abab".rfind("ab", 1, -4), -1)
assert_eq("abab".rfind("ab", 1, -3), -1)
assert_eq("abab".rfind("ab", 1, -2), -1)
assert_eq("abab".rfind("ab", 1, -1), -1)
assert_eq("abab".rfind("ab", 1, 0), -1)
assert_eq("abab".rfind("ab", 1, None), 2)
assert_eq("abab".rfind("ab", 1, 1), -1)
assert_eq("abab".rfind("ab", 1, 2), -1)
assert_eq("abab".rfind("ab", 1, 3), -1)
assert_eq("abab".rfind("ab", 1, 4), 2)
assert_eq("abab".rfind("ab", 1, 5), 2)
assert_eq("abab".rfind("ab", 2, -5), -1)
assert_eq("abab".rfind("ab", 2, -4), -1)
assert_eq("abab".rfind("ab", 2, -3), -1)
assert_eq("abab".rfind("ab", 2, -2), -1)
assert_eq("abab".rfind("ab", 2, -1), -1)
assert_eq("abab".rfind("ab", 2, 0), -1)
assert_eq("abab".rfind("ab", 2, None), 2)
assert_eq("abab".rfind("ab", 2, 1), -1)
assert_eq("abab".rfind("ab", 2, 2), -1)
assert_eq("abab".rfind("ab", 2, 3), -1)
assert_eq("abab".rfind("ab", 2, 4), 2)
assert_eq("abab".rfind("ab", 2, 5), 2)
assert_eq("abab".rfind("ab", 3, -5), -1)
assert_eq("abab".rfind("ab", 3, -4), -1)
assert_eq("abab".rfind("ab", 3, -3), -1)
assert_eq("abab".rfind("ab", 3, -2), -1)
assert_eq("abab".rfind("ab", 3, -1), -1)
assert_eq("abab".rfind("ab", 3, 0), -1)
assert_eq("abab".rfind("ab", 3, None), -1)
assert_eq("abab".rfind("ab", 3, 1), -1)
assert_eq("abab".rfind("ab", 3, 2), -1)
assert_eq("abab".rfind("ab", 3, 3), -1)
assert_eq("abab".rfind("ab", 3, 4), -1)
assert_eq("abab".rfind("ab", 3, 5), -1)
assert_eq("abab".rfind("ab", 4, -5), -1)
assert_eq("abab".rfind("ab", 4, -4), -1)
assert_eq("abab".rfind("ab", 4, -3), -1)
assert_eq("abab".rfind("ab", 4, -2), -1)
assert_eq("abab".rfind("ab", 4, -1), -1)
assert_eq("abab".rfind("ab", 4, 0), -1)
assert_eq("abab".rfind("ab", 4, None), -1)
assert_eq("abab".rfind("ab", 4, 1), -1)
assert_eq("abab".rfind("ab", 4, 2), -1)
assert_eq("abab".rfind("ab", 4, 3), -1)
assert_eq("abab".rfind("ab", 4, 4), -1)
assert_eq("abab".rfind("ab", 4, 5), -1)
assert_eq("abab".rfind("ab", 5, -5), -1)
assert_eq("abab".rfind("ab", 5, -4), -1)
assert_eq("abab".rfind("ab", 5, -3), -1)
assert_eq("abab".rfind("ab", 5, -2), -1)
assert_eq("abab".rfind("ab", 5, -1), -1)
assert_eq("abab".rfind("ab", 5, 0), -1)
assert_eq("abab".rfind("ab", 5, None), -1)
assert_eq("abab".rfind("ab", 5, 1), -1)
assert_eq("abab".rfind("ab", 5, 2), -1)
assert_eq("abab".rfind("ab", 5, 3), -1)
assert_eq("abab".rfind("ab", 5, 4), -1)
assert_eq("abab".rfind("ab", 5, 5), -1)


assert_fail("""'abc'.find('a', 0, 0, 0)""")
assert_fail("""'abc'.find('a', start = 0)""")
assert_fail("""'abc'.rfind('a', 0, 0, 0)""")
assert_fail("""'abc'.rfind('a', start = 0)""")

