assert_fail(""""abc"[-4]""")
assert_eq("abc"[-3], "a")
assert_eq("abc"[-2], "b")
assert_eq("abc"[-1], "c")
assert_eq("abc"[0], "a")
assert_eq("abc"[1], "b")
assert_eq("abc"[2], "c")
assert_fail(""""abc"[3]""")

assert_eq("Περιπτώσεις"[0], "Π")
assert_eq("Περιπτώσεις"[1], "ε")
assert_eq("Περιπτώσεις"[2], "ρ")
assert_eq("Περιπτώσεις"[3], "ι")
assert_eq("Περιπτώσεις"[4], "π")
assert_eq("Περιπτώσεις"[5], "τ")
assert_eq("Περιπτώσεις"[6], "ώ")
assert_eq("Περιπτώσεις"[7], "σ")
assert_eq("Περιπτώσεις"[8], "ε")
assert_eq("Περιπτώσεις"[9], "ι")
assert_eq("Περιπτώσεις"[10], "ς")
