assert_fail(""""abc".endswith()""")
assert_true("".endswith(""))
assert_false("".endswith("a"))
assert_true("abc".endswith("c"))
assert_true("abc".endswith("abc"))
assert_true("abc".endswith(""))
assert_false("abc".endswith("a"))
assert_false("abc".endswith("aabc"))
assert_false("abc".endswith(()))
assert_true("".endswith(("",)))
assert_false("".endswith(("a",)))
assert_true("abc".endswith(("c",)))
assert_true("abc".endswith(("abc",)))
assert_true("abc".endswith(("",)))
assert_false("abc".endswith(("a",)))
assert_false("abc".endswith(("aabc",)))
assert_fail(""""abc".endswith(b'')""")
assert_fail(""""abc".endswith((b'',))""")

assert_true("".endswith(("", "")))
assert_true("".endswith(("a", "")))
assert_true("abc".endswith(("c", "")))
assert_true("abc".endswith(("abc", "")))
assert_true("abc".endswith(("", "")))
assert_true("abc".endswith(("a", "")))
assert_true("abc".endswith(("aabc", "")))

assert_true("".endswith(("", "a")))
assert_false("".endswith(("a", "a")))
assert_true("abc".endswith(("c", "a")))
assert_true("abc".endswith(("abc", "a")))
assert_true("abc".endswith(("", "a")))
assert_false("abc".endswith(("a", "a")))
assert_false("abc".endswith(("aabc", "a")))

assert_true("".endswith(("", "c")))
assert_false("".endswith(("a", "c")))
assert_true("abc".endswith(("c", "c")))
assert_true("abc".endswith(("abc", "c")))
assert_true("abc".endswith(("", "c")))
assert_true("abc".endswith(("a", "c")))
assert_true("abc".endswith(("aabc", "c")))

assert_true("".endswith(("", "abc")))
assert_false("".endswith(("a", "abc")))
assert_true("abc".endswith(("c", "abc")))
assert_true("abc".endswith(("abc", "abc")))
assert_true("abc".endswith(("", "abc")))
assert_true("abc".endswith(("a", "abc")))
assert_true("abc".endswith(("aabc", "abc")))

assert_true("".endswith(("", "aabc")))
assert_false("".endswith(("a", "aabc")))
assert_true("abc".endswith(("c", "aabc")))
assert_true("abc".endswith(("abc", "aabc")))
assert_true("abc".endswith(("", "aabc")))
assert_false("abc".endswith(("a", "aabc")))
assert_false("abc".endswith(("aabc", "aabc")))

assert_fail(""""abc".endswith([])""")

assert_true("".endswith("", 0))
assert_false("".endswith("", 1))
assert_false("".endswith("a", 0))
assert_false("".endswith("a", 1))
assert_true("abc".endswith("c", 0))
assert_true("abc".endswith("c", 2))
assert_false("abc".endswith("c", 3))
assert_true("abc".endswith("abc", 0))
assert_false("abc".endswith("abc", 1))
assert_false("abc".endswith("abc", -1))
assert_false("abc".endswith("abc", -2))
assert_true("abc".endswith("abc", -3))
assert_true("abc".endswith("abc", -4))
assert_true("abc".endswith("", 0))
assert_true("abc".endswith("", 2))
assert_true("abc".endswith("", 3))
assert_false("abc".endswith("", 4))
assert_false("abc".endswith("a", 0))
assert_false("abc".endswith("a", 3))
assert_false("abc".endswith("aabc", -1))
assert_false("abc".endswith("aabc", 0))
assert_false("abc".endswith("aabc", 3))
assert_fail(""""abc".endswith("", True)""")
assert_true("abc".endswith("abc", None))

assert_true("".endswith("", 0, -1))
assert_true("".endswith("", 0, 0))
assert_false("".endswith("", 1, 0))
assert_false("".endswith("a", 0, 1))
assert_false("".endswith("a", 1, 1))
assert_true("abc".endswith("c", 0, 3))
assert_true("abc".endswith("c", 2, 3))
assert_false("abc".endswith("c", 3, 3))
assert_false("abc".endswith("c", 1, 2))
assert_true("abc".endswith("b", 1, 2))
assert_false("abc".endswith("abc", 0, -1))
assert_true("abc".endswith("ab", 0, -1))
assert_false("abc".endswith("abc", 0, 2))
assert_true("abc".endswith("abc", 0, 3))
assert_true("abc".endswith("abc", 0, 4))
assert_false("abc".endswith("abc", 1, 3))
assert_false("abc".endswith("abc", -1, 4))
assert_false("abc".endswith("abc", -2, 10))
assert_true("abc".endswith("", 0, 3))
assert_true("abc".endswith("", 2, 3))
assert_false("abc".endswith("", 2, 1))
assert_true("abc".endswith("", 3, 3))
assert_false("abc".endswith("", 4, 3))
assert_false("abc".endswith("a", 0, 3))
assert_true("abc".endswith("a", 0, 1))
assert_false("abc".endswith("a", 3, 3))
assert_false("abc".endswith("aabc", -1, 2))
assert_false("abc".endswith("aabc", 0, 4))
assert_false("abc".endswith("aabc", 3, 3))
 
assert_false("abab".endswith("ab", -5, -5))
assert_false("abab".endswith("ab", -5, -4))
assert_false("abab".endswith("ab", -5, -3))
assert_true("abab".endswith("ab", -5, -2))
assert_false("abab".endswith("ab", -5, -1))
assert_false("abab".endswith("ab", -5, 0))
assert_false("abab".endswith("ab", -5, 1))
assert_true("abab".endswith("ab", -5, 2))
assert_false("abab".endswith("ab", -5, 3))
assert_true("abab".endswith("ab", -5, 4))
assert_true("abab".endswith("ab", -5, 5))
assert_false("abab".endswith("ab", -4, -5))
assert_false("abab".endswith("ab", -4, -4))
assert_false("abab".endswith("ab", -4, -3))
assert_true("abab".endswith("ab", -4, -2))
assert_false("abab".endswith("ab", -4, -1))
assert_false("abab".endswith("ab", -4, 0))
assert_false("abab".endswith("ab", -4, 1))
assert_true("abab".endswith("ab", -4, 2))
assert_false("abab".endswith("ab", -4, 3))
assert_true("abab".endswith("ab", -4, 4))
assert_true("abab".endswith("ab", -4, 5))
assert_false("abab".endswith("ab", -3, -5))
assert_false("abab".endswith("ab", -3, -4))
assert_false("abab".endswith("ab", -3, -3))
assert_false("abab".endswith("ab", -3, -2))
assert_false("abab".endswith("ab", -3, -1))
assert_false("abab".endswith("ab", -3, 0))
assert_false("abab".endswith("ab", -3, 1))
assert_false("abab".endswith("ab", -3, 2))
assert_false("abab".endswith("ab", -3, 3))
assert_true("abab".endswith("ab", -3, 4))
assert_true("abab".endswith("ab", -3, 5))
assert_false("abab".endswith("ab", -2, -5))
assert_false("abab".endswith("ab", -2, -4))
assert_false("abab".endswith("ab", -2, -3))
assert_false("abab".endswith("ab", -2, -2))
assert_false("abab".endswith("ab", -2, -1))
assert_false("abab".endswith("ab", -2, 0))
assert_false("abab".endswith("ab", -2, 1))
assert_false("abab".endswith("ab", -2, 2))
assert_false("abab".endswith("ab", -2, 3))
assert_true("abab".endswith("ab", -2, 4))
assert_true("abab".endswith("ab", -2, 5))
assert_false("abab".endswith("ab", -1, -5))
assert_false("abab".endswith("ab", -1, -4))
assert_false("abab".endswith("ab", -1, -3))
assert_false("abab".endswith("ab", -1, -2))
assert_false("abab".endswith("ab", -1, -1))
assert_false("abab".endswith("ab", -1, 0))
assert_false("abab".endswith("ab", -1, 1))
assert_false("abab".endswith("ab", -1, 2))
assert_false("abab".endswith("ab", -1, 3))
assert_false("abab".endswith("ab", -1, 4))
assert_false("abab".endswith("ab", -1, 5))
assert_false("abab".endswith("ab", 0, -5))
assert_false("abab".endswith("ab", 0, -4))
assert_false("abab".endswith("ab", 0, -3))
assert_true("abab".endswith("ab", 0, -2))
assert_false("abab".endswith("ab", 0, -1))
assert_false("abab".endswith("ab", 0, 0))
assert_false("abab".endswith("ab", 0, 1))
assert_true("abab".endswith("ab", 0, 2))
assert_false("abab".endswith("ab", 0, 3))
assert_true("abab".endswith("ab", 0, 4))
assert_true("abab".endswith("ab", 0, 5))
assert_false("abab".endswith("ab", 1, -5))
assert_false("abab".endswith("ab", 1, -4))
assert_false("abab".endswith("ab", 1, -3))
assert_false("abab".endswith("ab", 1, -2))
assert_false("abab".endswith("ab", 1, -1))
assert_false("abab".endswith("ab", 1, 0))
assert_false("abab".endswith("ab", 1, 1))
assert_false("abab".endswith("ab", 1, 2))
assert_false("abab".endswith("ab", 1, 3))
assert_true("abab".endswith("ab", 1, 4))
assert_true("abab".endswith("ab", 1, 5))
assert_false("abab".endswith("ab", 2, -5))
assert_false("abab".endswith("ab", 2, -4))
assert_false("abab".endswith("ab", 2, -3))
assert_false("abab".endswith("ab", 2, -2))
assert_false("abab".endswith("ab", 2, -1))
assert_false("abab".endswith("ab", 2, 0))
assert_false("abab".endswith("ab", 2, 1))
assert_false("abab".endswith("ab", 2, 2))
assert_false("abab".endswith("ab", 2, 3))
assert_true("abab".endswith("ab", 2, 4))
assert_true("abab".endswith("ab", 2, 5))
assert_false("abab".endswith("ab", 3, -5))
assert_false("abab".endswith("ab", 3, -4))
assert_false("abab".endswith("ab", 3, -3))
assert_false("abab".endswith("ab", 3, -2))
assert_false("abab".endswith("ab", 3, -1))
assert_false("abab".endswith("ab", 3, 0))
assert_false("abab".endswith("ab", 3, 1))
assert_false("abab".endswith("ab", 3, 2))
assert_false("abab".endswith("ab", 3, 3))
assert_false("abab".endswith("ab", 3, 4))
assert_false("abab".endswith("ab", 3, 5))
assert_false("abab".endswith("ab", 4, -5))
assert_false("abab".endswith("ab", 4, -4))
assert_false("abab".endswith("ab", 4, -3))
assert_false("abab".endswith("ab", 4, -2))
assert_false("abab".endswith("ab", 4, -1))
assert_false("abab".endswith("ab", 4, 0))
assert_false("abab".endswith("ab", 4, 1))
assert_false("abab".endswith("ab", 4, 2))
assert_false("abab".endswith("ab", 4, 3))
assert_false("abab".endswith("ab", 4, 4))
assert_false("abab".endswith("ab", 4, 5))
assert_false("abab".endswith("ab", 5, -5))
assert_false("abab".endswith("ab", 5, -4))
assert_false("abab".endswith("ab", 5, -3))
assert_false("abab".endswith("ab", 5, -2))
assert_false("abab".endswith("ab", 5, -1))
assert_false("abab".endswith("ab", 5, 0))
assert_false("abab".endswith("ab", 5, 1))
assert_false("abab".endswith("ab", 5, 2))
assert_false("abab".endswith("ab", 5, 3))
assert_false("abab".endswith("ab", 5, 4))
assert_false("abab".endswith("ab", 5, 5))

assert_true("".endswith("", -1, -1))
assert_true("".endswith("", -1, 0))
assert_true("".endswith("", -1, 1))
assert_true("".endswith("", 0, -1))
assert_true("".endswith("", 0, 0))
assert_true("".endswith("", 0, 1))
assert_false("".endswith("", 1, -1))
assert_false("".endswith("", 1, 0))
assert_false("".endswith("", 1, 1))

assert_fail(""""abc".endswith("abc", 0, True)""")

assert_true("abc".endswith("abc", None, None))

assert_fail(""""abc".endswith("abc", 0, 0, 0)""")
assert_fail(""""abc".endswith("", start = 0)""")
