assert_fail("""'abc'.index()""")
assert_fail("""'abc'.index(())""")

assert_eq("banana".index(""), 0)
assert_eq("banana".index("an"), 1)
assert_eq("banana".index("ban"), 0)
assert_fail('''"banana".index("bb")''')

assert_fail("""'banana'.index('an', True)""")

assert_eq("abab".index("ab", -5), 0)
assert_eq("abab".index("ab", -4), 0)
assert_eq("abab".index("ab", -3), 2)
assert_eq("abab".index("ab", -2), 2)
assert_fail('''"abab".index("ab", -1)''')
assert_eq("abab".index("ab", 0), 0)
assert_eq("abab".index("ab", None), 0)
assert_eq("abab".index("ab", 1), 2)
assert_eq("abab".index("ab", 2), 2)
assert_fail('''"abab".index("ab", 3)''')
assert_fail('''"abab".index("ab", 4)''')
assert_fail('''"abab".index("ab", 5)''')

assert_eq("".index("", -1, -1), 0)
assert_eq("".index("", -1, 0), 0)
assert_eq("".index("", -1, None), 0)
assert_eq("".index("", -1, 1), 0)
assert_eq("".index("", 0, -1), 0)
assert_eq("".index("", None, -1), 0)
assert_eq("".index("", 0, 0), 0)
assert_eq("".index("", None, None), 0)
assert_eq("".index("", 0, 1), 0)
assert_eq("".index("", None, 1), 0)
assert_fail('''"".index("", 1, -1)''')
assert_fail('''"".index("", 1, 0)''')
assert_fail('''"".index("", 1, None)''')
assert_fail('''"".index("", 1, 1)''')

assert_fail('''"abab".index("ab", -5, -5)''')
assert_fail('''"abab".index("ab", -5, -4)''')
assert_fail('''"abab".index("ab", -5, -3)''')
assert_eq("abab".index("ab", -5, -2), 0)
assert_eq("abab".index("ab", -5, -1), 0)
assert_fail('''"abab".index("ab", -5, 0)''')
assert_eq("abab".index("ab", -5, None), 0)
assert_fail('''"abab".index("ab", -5, 1)''')
assert_eq("abab".index("ab", -5, 2), 0)
assert_eq("abab".index("ab", -5, 3), 0)
assert_eq("abab".index("ab", -5, 4), 0)
assert_eq("abab".index("ab", -5, 5), 0)
assert_fail('''"abab".index("ab", -4, -5)''')
assert_fail('''"abab".index("ab", -4, -4)''')
assert_fail('''"abab".index("ab", -4, -3)''')
assert_eq("abab".index("ab", -4, -2), 0)
assert_eq("abab".index("ab", -4, -1), 0)
assert_fail('''"abab".index("ab", -4, 0)''')
assert_eq("abab".index("ab", -4, None), 0)
assert_fail('''"abab".index("ab", -4, 1)''')
assert_eq("abab".index("ab", -4, 2), 0)
assert_eq("abab".index("ab", -4, 3), 0)
assert_eq("abab".index("ab", -4, 4), 0)
assert_eq("abab".index("ab", -4, 5), 0)
assert_fail('''"abab".index("ab", -3, -5)''')
assert_fail('''"abab".index("ab", -3, -4)''')
assert_fail('''"abab".index("ab", -3, -3)''')
assert_fail('''"abab".index("ab", -3, -2)''')
assert_fail('''"abab".index("ab", -3, -1)''')
assert_fail('''"abab".index("ab", -3, 0)''')
assert_eq("abab".index("ab", -3, None), 2)
assert_fail('''"abab".index("ab", -3, 1)''')
assert_fail('''"abab".index("ab", -3, 2)''')
assert_fail('''"abab".index("ab", -3, 3)''')
assert_eq("abab".index("ab", -3, 4), 2)
assert_eq("abab".index("ab", -3, 5), 2)
assert_fail('''"abab".index("ab", -2, -5)''')
assert_fail('''"abab".index("ab", -2, -4)''')
assert_fail('''"abab".index("ab", -2, -3)''')
assert_fail('''"abab".index("ab", -2, -2)''')
assert_fail('''"abab".index("ab", -2, -1)''')
assert_fail('''"abab".index("ab", -2, 0)''')
assert_eq("abab".index("ab", -2, None), 2)
assert_fail('''"abab".index("ab", -2, 1)''')
assert_fail('''"abab".index("ab", -2, 2)''')
assert_fail('''"abab".index("ab", -2, 3)''')
assert_eq("abab".index("ab", -2, 4), 2)
assert_eq("abab".index("ab", -2, 5), 2)
assert_fail('''"abab".index("ab", -1, -5)''')
assert_fail('''"abab".index("ab", -1, -4)''')
assert_fail('''"abab".index("ab", -1, -3)''')
assert_fail('''"abab".index("ab", -1, -2)''')
assert_fail('''"abab".index("ab", -1, -1)''')
assert_fail('''"abab".index("ab", -1, 0)''')
assert_fail('''"abab".index("ab", -1, None)''')
assert_fail('''"abab".index("ab", -1, 1)''')
assert_fail('''"abab".index("ab", -1, 2)''')
assert_fail('''"abab".index("ab", -1, 3)''')
assert_fail('''"abab".index("ab", -1, 4)''')
assert_fail('''"abab".index("ab", -1, 5)''')
assert_fail('''"abab".index("ab", 0, -5)''')
assert_fail('''"abab".index("ab", None, -5)''')
assert_fail('''"abab".index("ab", 0, -4)''')
assert_fail('''"abab".index("ab", None, -4)''')
assert_fail('''"abab".index("ab", 0, -3)''')
assert_fail('''"abab".index("ab", None, -3)''')
assert_eq("abab".index("ab", 0, -2), 0)
assert_eq("abab".index("ab", None, -2), 0)
assert_eq("abab".index("ab", 0, -1), 0)
assert_eq("abab".index("ab", None, -1), 0)
assert_fail('''"abab".index("ab", 0, 0)''')
assert_eq("abab".index("ab", None, None), 0)
assert_fail('''"abab".index("ab", 0, 1)''')
assert_fail('''"abab".index("ab", None, 1)''')
assert_eq("abab".index("ab", 0, 2), 0)
assert_eq("abab".index("ab", None, 2), 0)
assert_eq("abab".index("ab", 0, 3), 0)
assert_eq("abab".index("ab", None, 3), 0)
assert_eq("abab".index("ab", 0, 4), 0)
assert_eq("abab".index("ab", None, 4), 0)
assert_eq("abab".index("ab", 0, 5), 0)
assert_eq("abab".index("ab", None, 5), 0)
assert_fail('''"abab".index("ab", 1, -5)''')
assert_fail('''"abab".index("ab", 1, -4)''')
assert_fail('''"abab".index("ab", 1, -3)''')
assert_fail('''"abab".index("ab", 1, -2)''')
assert_fail('''"abab".index("ab", 1, -1)''')
assert_fail('''"abab".index("ab", 1, 0)''')
assert_eq("abab".index("ab", 1, None), 2)
assert_fail('''"abab".index("ab", 1, 1)''')
assert_fail('''"abab".index("ab", 1, 2)''')
assert_fail('''"abab".index("ab", 1, 3)''')
assert_eq("abab".index("ab", 1, 4), 2)
assert_eq("abab".index("ab", 1, 5), 2)
assert_fail('''"abab".index("ab", 2, -5)''')
assert_fail('''"abab".index("ab", 2, -4)''')
assert_fail('''"abab".index("ab", 2, -3)''')
assert_fail('''"abab".index("ab", 2, -2)''')
assert_fail('''"abab".index("ab", 2, -1)''')
assert_fail('''"abab".index("ab", 2, 0)''')
assert_eq("abab".index("ab", 2, None), 2)
assert_fail('''"abab".index("ab", 2, 1)''')
assert_fail('''"abab".index("ab", 2, 2)''')
assert_fail('''"abab".index("ab", 2, 3)''')
assert_eq("abab".index("ab", 2, 4), 2)
assert_eq("abab".index("ab", 2, 5), 2)
assert_fail('''"abab".index("ab", 3, -5)''')
assert_fail('''"abab".index("ab", 3, -4)''')
assert_fail('''"abab".index("ab", 3, -3)''')
assert_fail('''"abab".index("ab", 3, -2)''')
assert_fail('''"abab".index("ab", 3, -1)''')
assert_fail('''"abab".index("ab", 3, 0)''')
assert_fail('''"abab".index("ab", 3, None)''')
assert_fail('''"abab".index("ab", 3, 1)''')
assert_fail('''"abab".index("ab", 3, 2)''')
assert_fail('''"abab".index("ab", 3, 3)''')
assert_fail('''"abab".index("ab", 3, 4)''')
assert_fail('''"abab".index("ab", 3, 5)''')
assert_fail('''"abab".index("ab", 4, -5)''')
assert_fail('''"abab".index("ab", 4, -4)''')
assert_fail('''"abab".index("ab", 4, -3)''')
assert_fail('''"abab".index("ab", 4, -2)''')
assert_fail('''"abab".index("ab", 4, -1)''')
assert_fail('''"abab".index("ab", 4, 0)''')
assert_fail('''"abab".index("ab", 4, None)''')
assert_fail('''"abab".index("ab", 4, 1)''')
assert_fail('''"abab".index("ab", 4, 2)''')
assert_fail('''"abab".index("ab", 4, 3)''')
assert_fail('''"abab".index("ab", 4, 4)''')
assert_fail('''"abab".index("ab", 4, 5)''')
assert_fail('''"abab".index("ab", 5, -5)''')
assert_fail('''"abab".index("ab", 5, -4)''')
assert_fail('''"abab".index("ab", 5, -3)''')
assert_fail('''"abab".index("ab", 5, -2)''')
assert_fail('''"abab".index("ab", 5, -1)''')
assert_fail('''"abab".index("ab", 5, 0)''')
assert_fail('''"abab".index("ab", 5, None)''')
assert_fail('''"abab".index("ab", 5, 1)''')
assert_fail('''"abab".index("ab", 5, 2)''')
assert_fail('''"abab".index("ab", 5, 3)''')
assert_fail('''"abab".index("ab", 5, 4)''')
assert_fail('''"abab".index("ab", 5, 5)''')

assert_fail("""'abc'.index('a', 0, 0, 0)""")
assert_fail("""'abc'.index('a', start = 0)""")

