assert_eq("abc".count(""), 4)
assert_eq("banana".count("a"), 3)
assert_eq("aaaaaa".count("aa"), 3)
assert_eq("aaaaaaa".count("aa"), 3)
assert_eq("banana".count("a", 0), 3)
assert_eq("banana".count("a", 1), 3)
assert_eq("banana".count("a", 2), 2)
assert_eq("banana".count("a", 3), 2)
assert_eq("banana".count("a", 4), 1)
assert_eq("banana".count("a", 5), 1)
assert_eq("banana".count("a", 6), 0)
assert_eq("banana".count("a", 7), 0)
assert_eq("banana".count("a", None), 3)
assert_eq("banana".count("a", 0, 100), 3)
assert_eq("banana".count("a", 0, -1), 2)
assert_eq("banana".count("a", 0, None), 3)
assert_eq("abc".count("", 1, 1), 1)
assert_eq("abc".count("", 1, 0), 0)

