# Copyright 2024-2025 Lucas Mirelmann

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "logging",
    srcs = ["logging.cpp"],
    hdrs = ["logging.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//grammar:token",
    ],
)

