assert_eq(abs(-1), 1)
assert_eq(any([True, False]), True)
assert_eq(all([True, False]), False)
assert_eq(bool(1), True)
assert_eq(bytes("abc"), b"abc")
assert_eq(chr(1), "\x01")
assert_eq(dict(), {})
assert_eq(dict({}), {})
assert_eq(dict({'a': 1}), {'a': 1})
assert_eq(dict({'a': 1}, b = 2), {'a': 1, 'b': 2})
assert_eq(dict([('a', 1), ('b', 2)]), {'a': 1, 'b': 2})
assert_eq(str(dict(one = 1, two = 2, three = 3, four = 4)), '{"one": 1, "two": 2, "three": 3, "four": 4}')
assert_eq(dir(1), [])
assert_eq(dir({}), ["clear", "get", "items", "keys", "pop", "popitem", "setdefault", "update", "values"])
assert_eq(enumerate(['a', 'b', 'c']), [(0, 'a'), (1, 'b'), (2, 'c')])
assert_eq(enumerate(['a', 'b', 'c'], start = 100), [(100, 'a'), (101, 'b'), (102, 'c')])
assert_fail("fail('Some message')", error_message = "Error: Some message")
assert_fail("float('2e308')", error_message = "OverflowError: floating-point number too large")
assert_eq(float(0.0), 0.0)
assert_eq(float(1), 1.0)
assert_eq(float("Inf"), 1e308*10)
assert_eq(float("-Inf"), -1e308*10)
l = []
assert_eq(getattr(l, "append"), l.append)
assert_eq(hasattr(b'', "elems"), True)
assert_eq(hash("abc"), 6041520446639342335)
assert_eq(int("0123", 10), 123)
assert_eq(int("0123"), 123)
assert_fail('int("0123", 0)', error_message = "ValueError: invalid literal for int() with base 0: '0123'")
assert_eq(len([]), 0)
assert_eq(list((1, 2)), [1, 2])
assert_eq(max(1, 2, 3), 3)
assert_eq(max("one", "two", "three", key = len), "three")
assert_eq(max("one", "two", "three", key = lambda x: len(x)), "three")
assert_eq(min(1, 2, 3), 1)
assert_eq(min("one", "two", "three", key = len), "one")
assert_eq(min("one", "two", "three", key = lambda x: len(x)), "one")
assert_eq(ord(b'\xff'), 255)
assert_eq(ord("😃"), 128515)
assert_succeed("""print("abc")""", print = "abc\n")
assert_eq(list(range(3, 8, 2)), [3, 5, 7])
assert_eq(repr([1, 2]), "[1, 2]")
assert_eq(reversed(range(5)), [4, 3, 2, 1, 0])
assert_eq(repr(set([1, 2, 3])), "set([1, 2, 3])")
# TODO(lmirelmann): sorted
assert_eq(str("abc"), 'abc')
assert_eq(tuple(range(3)), (0, 1, 2))
assert_eq(type([]), 'list')
assert_eq(zip(range(100), range(3, 5)), [(0, 3), (1, 4)])

