# Copyright 2026 Lucas Mirelmann

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//native:__subpackages__"])

cc_library(
    name = "starlark_module_abi",
    hdrs = ["starlark_module_abi.hpp"],
)
