print()
print("a")
print("b", "c")
print("d", "e", "f")
print(sep = " ")
print(sep = " ", end = "\n")
print("g", sep = " ")
print("h", sep = " ", end = "\n")
print("i", *["a"])
print("j", **dict(sep = " "))
print(sep = " ", *["a"])
print(end = " ", **dict(sep = " "))
print(*["a"], **dict(sep = " "))

print(end = " ", *["a"], **dict(sep = " "))
print("k", *["a"], **dict(sep = " "))
print("l", end = " ", **dict(sep = " "))
print("m", end = " ", *["a"])

print("n", end = " ", *["a"], **dict(sep = " "))
print(*["a"])
print(**dict(sep = " "))
