# Copyright 2026 Lucas Mirelmann

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "status",
    srcs = ["status.cpp"],
    hdrs = ["status.hpp"],
    visibility = ["//visibility:public"],
)
