edition = "2024";

package starlark.bytecode;

import "proto/starlark_logging.proto";

message Program {
  repeated Block block = 1;
  repeated string const_string = 2;
}

message Block {
  repeated OpCode op_code = 1;
  FunctionSignature function_signature = 2;
}

message OpCode {
  // next_id: 110
  oneof op_code {
    // There are no op codes for `True` and `False` as they are not reserved words.
    // https://github.com/bazelbuild/starlark/issues/312
    ConstBigInt const_big_int = 1;
    ConstInt const_int = 67;
    ConstFloat const_float = 2;
    ConstString const_string = 3;
    ConstString const_string_view = 106;
    ConstBytes const_bytes = 4;
    ConstNone const_none = 59;

    Pop pop = 5;

    UnaryPlus unary_plus = 7;
    UnaryMinus unary_minus = 8;
    UnaryTilde unary_tilde = 9;
    UnaryNot unary_not = 10;

    BinaryEqualsEquals binary_equals_equals = 11;
    BinaryBangEquals binary_bang_equals = 12;
    BinaryLessThan binary_less_than = 13;
    BinaryGreateThan binary_greater_than = 14;
    BinaryLessThanEquals binary_less_than_equals = 15;
    BinaryGreaterThanEquals binary_greater_than_equals = 16;
    BinaryIn binary_in = 17;
    BinaryNotIn binary_not_in = 18;
    BinaryPipe binary_pipe = 19;
    BinaryHat binary_hat = 20;
    BinaryAmpersand binary_ampersand = 21;
    BinaryLessThanLessThan binary_less_than_less_than = 22;
    BinaryGreaterThanGreaterThan binary_greater_than_greater_than = 23;
    BinaryMinus binary_minus = 24;
    BinaryPlus binary_plus = 25;
    BinaryStar binary_star = 26;
    BinaryPercent binary_percent = 27;
    BinarySlash binary_slash = 28;
    BinarySlashSlash binary_slash_slash = 29;

    JumpAddress goto = 30;
    JumpAddress jump_if_false = 32;
    JumpAddress jump_if_true_or_pop = 31;
    JumpAddress jump_if_false_or_pop = 6;

    MakeTuple make_tuple = 33;
    MakeList make_list = 34;
    AddToList add_to_list = 35;
    MakeDictionary make_dictionary = 36;
    AddToDictionary add_to_dictionary = 37;

    PosInFrame load = 38;
    PosInFrame store = 39;

    GetIterator get_iterator = 40;
    ForIterator for_iterator = 41;
    ForIterator for_iterator_ext = 109;
    EndIterator end_iterator = 42;

    Unpack unpack = 70;
    PosInFrame assign_plus_equals = 44;
    PosInFrame assign_minus_equals = 45;
    PosInFrame assign_star_equals = 46;
    PosInFrame assign_slash_equals = 47;
    PosInFrame assign_slash_slash_equals = 48;
    PosInFrame assign_percent_equals = 49;
    PosInFrame assign_ampersand_equals = 50;
    PosInFrame assign_pipe_equals = 51;
    PosInFrame assign_hat_equals = 52;
    PosInFrame assign_less_less_equals = 53;
    PosInFrame assign_greater_greater_equals = 54;

    DotMember dot_member = 55;
    DotMember assign_dot_member = 43;
    DotMember assign_dot_member_plus_equals = 73;
    DotMember assign_dot_member_minus_equals = 74;
    DotMember assign_dot_member_star_equals = 75;
    DotMember assign_dot_member_slash_equals = 76;
    DotMember assign_dot_member_slash_slash_equals = 77;
    DotMember assign_dot_member_percent_equals = 78;
    DotMember assign_dot_member_ampersand_equals = 79;
    DotMember assign_dot_member_pipe_equals = 80;
    DotMember assign_dot_member_hat_equals = 81;
    DotMember assign_dot_member_less_less_equals = 82;
    DotMember assign_dot_member_greater_greater_equals = 83;

    IndexMember index_member = 60;
    IndexMember assign_index_member = 68;
    IndexMember assign_index_member_plus_equals = 84;
    IndexMember assign_index_member_minus_equals = 85;
    IndexMember assign_index_member_star_equals = 86;
    IndexMember assign_index_member_slash_equals = 87;
    IndexMember assign_index_member_slash_slash_equals = 88;
    IndexMember assign_index_member_percent_equals = 89;
    IndexMember assign_index_member_ampersand_equals = 90;
    IndexMember assign_index_member_pipe_equals = 91;
    IndexMember assign_index_member_hat_equals = 92;
    IndexMember assign_index_member_less_less_equals = 93;
    IndexMember assign_index_member_greater_greater_equals = 94;

    SliceRange slice_range = 61;
    SliceRange assign_slice_range = 69;
    SliceRange assign_slice_range_plus_equals = 95;
    SliceRange assign_slice_range_minus_equals = 96;
    SliceRange assign_slice_range_star_equals = 97;
    SliceRange assign_slice_range_slash_equals = 98;
    SliceRange assign_slice_range_slash_slash_equals = 99;
    SliceRange assign_slice_range_percent_equals = 100;
    SliceRange assign_slice_range_ampersand_equals = 101;
    SliceRange assign_slice_range_pipe_equals = 102;
    SliceRange assign_slice_range_hat_equals = 103;
    SliceRange assign_slice_range_less_less_equals = 104;
    SliceRange assign_slice_range_greater_greater_equals = 105;

    Call call = 56;
    LoadModule load_module = 57;
    Return return = 62;

    MakeFunction make_function = 63;

    CreateFrame create_frame = 65;
    PopFrame pop_frame = 66;

    End end = 58;
    Fail fail = 71;
    Nop nop = 108;
  }
  SourceHighlight sh = 107;
}

message ConstNone {}

message ConstInt {
  int64 value = 1;
}

message ConstBigInt {
  string value = 1;
}

message ConstFloat {
  double value = 1;
}

message ConstString {
  int64 const_string_pos = 1;
}

message ConstBytes {
  string value = 1;
}

message Pop {}
message UnaryPlus {}
message UnaryMinus {}
message UnaryTilde {}
message UnaryNot {}
message BinaryEqualsEquals {}
message BinaryBangEquals {}
message BinaryLessThan {}
message BinaryGreateThan {}
message BinaryLessThanEquals {}
message BinaryGreaterThanEquals {}
message BinaryIn {}
message BinaryNotIn {}
message BinaryPipe {}
message BinaryHat {}
message BinaryAmpersand {}
message BinaryLessThanLessThan {}
message BinaryGreaterThanGreaterThan {}
message BinaryMinus {}
message BinaryPlus {}
message BinaryStar {}
message BinaryPercent {}
message BinarySlash {}
message BinarySlashSlash {}

message JumpAddress {
  int32 address_delta = 1;
}

message MakeTuple {
  uint32 number_of_elements = 1;
}

message MakeList {
  uint32 reserve_size = 1;
}
message AddToList {
  uint32 number_of_elements = 1;
}

message MakeDictionary {
  uint32 reserve_size = 1;
}
message AddToDictionary {
  uint32 number_of_elements = 1;
}

message PosInFrame {
  int64 frame = 1;
  int64 pos_in_frame = 2;
}

message GetIterator {}
message ForIterator {
  int32 address_delta = 1;
}
message EndIterator {}

message Unpack {
  uint32 number_of_elements = 1;
}

message DotMember {
  string member = 1;
}

message IndexMember {}
message SliceRange{}

message Call {
  int32 positional_arguments_count = 1;
  int32 named_arguments_count = 2;
  bool has_variadic_positional_argument = 3;
  bool has_variadic_named_argument = 4;
}

message LoadModule {
  string module = 1;
  repeated Value value = 2;
  message Value {
    string remote_symbol = 1;
    PosInFrame pos = 2;
  }
}

message Return {}

message MakeFunction {
  uint32 entrypoint = 1;
  uint32 default_values_count = 2;
}

message CreateFrame {
  BlockType block_type = 1;
  repeated string symbol = 2;
}

enum BlockType {
  BLOCK_TYPE_UNDEFINED = 0;
  PREDECLARED_BLOCK = 1;
  MODULE_BLOCK = 2;
  FILE_BLOCK = 3;
  FUNCTION_BLOCK = 4;
  COMPREHENSION_BLOCK = 5;
}

message PopFrame {}

message Nop {}
message End {}
message Fail {}

message FunctionSignature {
  repeated Param param = 1;
  bool has_star_argument = 2;
  bool has_star_star_argument = 3;
  uint64 keyword_only_parameter_count = 4;
  string fn_name = 5;
  message Param {
    string name = 1;
    PosInFrame pos = 2;
    bool default_initialization = 3;
  }
}

message SourceHighlight {
  starlark.logging.Position start = 1;
  starlark.logging.Position highlight_start = 2;
  starlark.logging.Position highlight_end = 3;
  starlark.logging.Position end = 4;
}

