syntax = "proto3";

package starlark.bytecode;

message Program {
  repeated OpCode op_code = 1;
}

message OpCode {
  oneof op_code {
    // TODO(lmirelmann): `None`, `True` and `False` are not reserved words.
    //     https://github.com/bazelbuild/starlark/issues/312
    ConstInt const_int = 1;
    ConstFloat const_float = 2;
    ConstString const_string = 3;
    ConstBytes const_bytes = 4;
    Drop drop = 5;
  }
}

message ConstInt {
  string value = 1;
}

message ConstFloat {
  double value = 1;
}

message ConstString {
  string value = 1;
}

message ConstBytes {
  string value = 1;
}
message Drop {}

