# Copyright 2026 Lucas Mirelmann

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "runtime_error_messages",
    srcs = ["runtime_error_messages.cpp"],
    hdrs = ["runtime_error_messages.hpp"],
    visibility = ["//visibility:public"],
)

